### ISSUE TITLE
RemoveXXXIDs throwing error for non-nullable O2M relation

### ISSUE THREAD

**Issue by mwoelk** [ent/ent#3714] opened 2023-08-25 14:59 UTC
We have a schema with two entities (Product, Property) with a O2M relation. Because a property should never exist without a product, the `product_id` field in the property table should be non-nullable.

```go
// schema/product.go

// Fields of the Product.
func (Product) Fields() []ent.Field {
	return []ent.Field{
		field.String("name"),
	}
}

// Edges of the Product.
func (Product) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("properties", Property.Type).
			Ref("product"),
	}
}
```

```go
// schema/property.go

// Fields of the Property.
func (Property) Fields() []ent.Field {
	return []ent.Field{
		field.Int("product_id").
			Immutable(),
		field.String("name"),
		field.String("value"),
	}
}

// Edges of the Property.
func (Property) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("product", Product.Type).
			Unique().
			Required().
			Field("product_id").
			Immutable(),
	}
}
```

Using `RemovePropertyIDs` when updating a product throws an error (which is btw. misleading due to what seems copy paste isue with the error itself):
`add O2M edge for table properties: NOT NULL constraint failed: properties.product_id` 

This is due to `sqlgraph.clearFKEdges` trying to set the field to NULL instead of deleting the entity on the other side of the relation [here](https://github.com/ent/ent/blob/62a3e6f203184f97873b08fab6137f4f37044fc5/dialect/sql/sqlgraph/graph.go#L1766).

There should either be some checks if an edge was marked as required in order to delete it instead of trying to setting it to null or the RemoveXXXIDs functions should not be generated in this case at all.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Using RemovePropertyIDs when updating a product throws an error.

## Expected Behavior 🤔

It should not throw an error but delete the entity on the other side of the relation.

## Steps to Reproduce 🕹

Reproduction Repo:
https://github.com/mwoelk/bug

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.21.0  |
| Ent         | 0.12.3   |
| Database    | SQLite, Postgres   |
| Driver      |   github.com/mattn/go-sqlite3,  github.com/lib/pq   |

**Comment by a8m** [comment] 2023-08-25 15:26
Hey @mwoelk 👋 

If you want to delete a property (or multiple), you need to use the `client.Property` builder for this. The `Product` builder cannot delete a property as there are no deletion rules for this on the database side (you can still implement such "delete orphan" logic on the client side using a generic hook). There's no extra cost for executing another statement on `client.Property` because updating a property requires executing another statement on the properties table anyway.

Closing, but please feel free to join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎

**Closed by a8m** 2023-08-25 15:26 UTC

**Comment by mwoelk** [comment] 2023-08-25 17:06
Hey @a8m,
Ent generates the `client.Product.Update(prod).RemovePropertyIDs(ids...)` method. 

It works fine with nullable relations (by triggering additional queries). But it's missing a check to see if the other side of the relation is required and just tries to update it by setting the field to NULL. See here: https://github.com/ent/ent/blob/62a3e6f203184f97873b08fab6137f4f37044fc5/dialect/sql/sqlgraph/graph.go#L1765-L1768

I've just finished fixing this and will submit a PR shortly after some more testing. 
Without this fix, `removePropertyIDs` and `clearProperties` in generated update-mutations for graphql won't work as well for O2M relations with required inverse edges.

Have you checked out the reproduction repo?
https://github.com/mwoelk/bug

**Comment by a8m** [comment] 2023-08-25 17:40
Thanks for the response, @mwoelk. 

Relations can be recursive, for example, a `Property` that points to many `PropertyValue`s. Hence, there is a reason why "delete orphan" is not implemented in the framework, and the suggested solution is that users will implement this using hooks as this info exists there - this is what I use in the last years. 

As you can see - from the framework perspective, this is not a bug, because the implementation today is intentional - we don’t add extra logic/magic/operations that are not ~100% correct.

**Comment by a8m** [comment] 2023-08-25 18:05
One final point, @mwoelk: data deletion is a destructive change. Currently, the only records (rows) we implicitly delete are M2M edges, as they don’t contain actual data. I assume that most users like me wouldn’t expect the framework to implicitly delete nodes, which represent real data.

I truly value and appreciate your contribution. However, I believe using hooks might be the right way to implement this. I’d recommend exploring that option. Thank you for understanding 🙏🏻

**Comment by mwoelk** [comment] 2023-08-25 18:51
Hey @a8m,
Thanks for the explanation. I fully agree that magic `orphan removal` should not be implemented. I already use quite a few hooks to do that as well. My issue here is that those operations are also created as part of the GraphQL update mutation. 
In my case I have a product with properties and a user might perform a product update using a mutation with `removePropertyIDs`.  

Let's assume there might be a nested relations e.g. the mentioned PropertyValues you mentioned or other cleanup logic that should go inside a hook. Furthermore a `ProductProperty` is required to only exist together with a `Product`.

**Case 1: Current state - your recommended approach**
1. `ProductProperty` has an edge to `Product` that is _not marked as required_ (otherwise we would get a DB error when it will be set to null later on)
2. When `RemoveProductPropertyIDs` is called during product update, it sets the `ProductID` of the properties to NULL
3. An _update_-hook on `ProductProperty` should now check if a `ProductID` is null and then deletes `PropertyValues`, runs some cleanup and deletes the `Property` itself
4. In addition a second hook is required that listens on _deletion_ of a `Property` in order to delete `PropertyValues` as well
5. Another hook is required to make sure that `ProductID` is set during _creation_ and may not be updated to another ID except NULL during _updates_

**Case 2: My proposal**
1. `ProductProperty` has an edge to `Product` that is _marked as required_ 
2. When `RemoveProductPropertyIDs` is called during product update, it triggers deletion of the `ProductProperty` 
3. A single _delete_-hook on `ProductProperty` deletes the `PropertyValues` 
4. No other hooks are necessary (the edge marked as required ensures presence of `ProductID` at creation.

**Improvements**
- Handling of nested relations can be handled by a single delete-hook (same logic applies no matter if it's deleted directly or through a relation)
- No need for destructive logic inside an update hook. It just seems weird to me to use an update-hook to delete the entity itself.
- If there is a privacy rule in place that differentiates between update/delete permissions no additional checks (was ID set to NULL during update == delete) are required
- If there are no nested relations, it just works as expected especially with generated graphql inputs
- If there are nested relations and no hooks, the same behaviour happens as if a regular delete would be called on the entity so nothing surprising. 
- Using required and therefore a db-level NOT NULL enforce the requirement that a property cannot exist without a product on a DB-level as well

**Opinion/Questions**
- In my opinion, a call to `RemoveProductPropertyIDs` if (and only if) the inverse edge is marked as required, should trigger a delete of this entity. Even the database enforces it by not letting it be set to null. It shouldn't exist in this state. And the word `Remove` implies very well that there is a destructive change happening
- In fact I was totally surprised when I stumbled over this issue because just based on the naming and the underlying database constraints I expected it to work this way because I couldn't imagine any other plausible way the function would work if the field is not nullable :)
- Why does the .Required() annotation even exist for edges and sets the FK-field as NOT NULL? If it only exists to check presence of the FK during creation, the field shouldn't be NOT NULL in order for your approach to work otherwise it throws an error when trying to set it to null as currently implemented.
- Why are `RemovePropertyIDs` or `ClearPropertyIDs` methods created if it is expected for them to throw an error and not be supported in this situation?

**Clarification**
My proposal is to only fix the behaviour in this specific case:
- M2O-edge
- the inverse direction is **required** i.e. a Property should never exist without a Product and FK cannot be NULL
- only during update of product when `RemovePropertyIDs` or `ClearPropertyIDs` are called

Feel free to check out / try out my PR. In my opinion it's just a few lines of code that can make it easier to use ent, allows to use a method that should not exist, and make things more predictable (multiple hooks vs. a single hook, uniform privacy rules, etc.). But maybe I'm looking at it the wrong way and there is an even easier way to achieve what you proposed.

**Comment by a8m** [comment] 2023-08-25 19:12
Thanks for the detailed answer. Unfortunately, I don't have time at the moment to address everything. But regarding the main parts: the `Required()` option dictates that the edge must be provided upon creation (and it can't be null when being updated).

We can't trigger DELETE operations on `sqlgraph` because it's not aware of the entire schema and is completely detached from the hooks system. Edges/Relations represent a graph. If you delete one node, you might encounter other constraint violations, so we offload this responsibility to the user. Furthermore, we can't implicitly delete data in Ent – that's not how the framework operates - implicitly deleting one record might cascade this to other records, etc. In the GraphQL context, users use `entgql` transactional mutations where all operations are grouped in a transaction. The pattern of deleting records in the hook is common – if a mutation is aborted, the entire transaction is rolled back.

To implement the "delete orphan" logic, we take a different approach. We check for `Removed<E>IDs` on specific root mutations, delete them, and then clear the mutation reset IDs. The hook mechanism manages the nested deletion.

Concerning naming - we use Remove/Clear for all edges. This is the convention adopted within the framework. They can't be removed or changed, because we actually use them and this is also a breaking change.

**Comment by a8m** [comment] 2023-08-25 19:15
> Why are `RemovePropertyIDs` or `ClearProperties` methods created if it is expected for them to throw an error and not be supported in this situation?

That's a good question - the `Required()` option predates the `NOT NULL` configuration. There were multiple discussions about it, and this was changed more than a year ago.

**Comment by mwoelk** [comment] 2023-08-25 20:49
Wow. 🙏 Thank you for your time and this detailed explanation on the inner workings of ent.
I definitely need to dive in a little deeper as soon as I have some more spare time.

I assumed that the subsequent queries in sqlgraph would trigger hooks as well. This would also imply that with the current logic (for nullable FKs i.e. entities that can exist without their parent) `Remove<E>IDs`  wouldn't trigger any hooks in `<E>` e.g. a hook to set an update timestamp? Or a hook to set the user who last updated the entity. 

Somehow I got the feeling that these methods shouldn't be part of the framework at all as they "are not ~100% correct" as you stated above 😂 Maybe the user should just extend the graphql input and apply the logic you described above. 

 But as this would be a breaking change indeed maybe it's best to just:
- fix the [error message](https://github.com/ent/ent/blob/62a3e6f203184f97873b08fab6137f4f37044fc5/dialect/sql/sqlgraph/graph.go#L1770) to make sense 
- add a hint to the docs (either on the "Edges" or "CRUD API" page) about how these methods work/are supposed to work
- maybe generate the `<E>UpdateOne.Remove<E>IDs` and `<E>UpdateOne.Clear<E>s` differently for this case (required inverse edge) so an error "cannot remove/clear edges with a required foreign key" is returned and improve the comments for these methods to recommend hooks / link to docs

@a8m What do you think? 
Let me know and I'll cook up a new PR so others might find a solution quickly if they have the same problem.
