### ISSUE TITLE
"No database selected" error while creating schema with alternate schema option

### ISSUE THREAD

**Issue by arunjohn99** [ent/ent#1619] opened 2021-06-01 20:32 UTC
Hi @a8m,

When i execute the below API, it is throwing "No database selected" error

```
client.Schema.Create(context.Background(), migrate.WithDropIndex(true),
		migrate.WithDropColumn(true))
```

I have my tables spread across multiple schemas and initialize ent client with Alternate schema option. 

```
client := ent.NewClient(ent.Driver(drv), ent.AlternateSchema(ent.SchemaConfig{
		//schema1
                 Table1:   Schema1,
                 Table2:   Schema1,

                //schema2
		Table1: Schema2,
	}))

```
I am using 0.8.0

Let me know if you need me to file a defect?

**Comment by a8m** [comment] 2021-06-02 11:32
Hey @arunjohn99, please see the workaround for this in https://github.com/ent/ent/issues/1564 and also my comment about the contribution and the planned support for this feature. 

Closing as this is a duplicate of https://github.com/ent/ent/issues/1564 🙏

**Closed by a8m** 2021-06-02 11:32 UTC
