### ISSUE TITLE
Panic (re)-generating assets

### ISSUE THREAD

**Issue by TheBeachMaster** [ent/ent#2938] opened 2022-09-18 15:23 UTC
(Re)-generating assets fails with a panic.

I removed the originally generated `ent.graphql` and run the the generate commands and the process fails

Of interest is this line in the error output

```
panic: template: setter.tmpl:69: unexpected " " in in {{continue}}

```

The contents of my `entc.go` are as follows

```go
//go:build ignore
// +build ignore

package main

import (
	"log"

	"entgo.io/contrib/entgql"
	"entgo.io/ent/entc"
	"entgo.io/ent/entc/gen"
)

func main() {
	ex, err := entgql.NewExtension(
		entgql.WithWhereFilters(true),
		entgql.WithConfigPath("./gqlgen.yml"),
		entgql.WithSchemaGenerator(),
		entgql.WithSchemaPath("./graphql/ent.graphqls"),
	)
	if err != nil {
		log.Fatalf("error creating entgql extension: %v", err)
	}
	err = entc.Generate("./ent/schema", &gen.Config{}, entc.Extensions(ex)) // This is line 24
	if err != nil {
		log.Fatalf("running ent codegen failed: %v", err)
	}
}
```

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

> cmd
```sh
  go run -mod=mod ./ent/entc.go 
```

> output
```
panic: template: setter.tmpl:69: unexpected " " in in {{continue}}

goroutine 1 [running]:
entgo.io/ent/entc/gen.MustParse(...)
	/Users/<>/go/pkg/mod/entgo.io/ent@v0.11.3-0.20220830071904-3b1b75b9d7a9/entc/gen/template.go:341
entgo.io/ent/entc/gen.initTemplates()
	/Users/<>/go/pkg/mod/entgo.io/ent@v0.11.3-0.20220830071904-3b1b75b9d7a9/entc/gen/template.go:227 +0x73b
entgo.io/ent/entc/gen.(*Graph).templates(0xc00077ac80)
	/Users/<>/go/pkg/mod/entgo.io/ent@v0.11.3-0.20220830071904-3b1b75b9d7a9/entc/gen/graph.go:791 +0x36
entgo.io/ent/entc/gen.generate(0xc00077ac80)
	/Users/<>/go/pkg/mod/entgo.io/ent@v0.11.3-0.20220830071904-3b1b75b9d7a9/entc/gen/graph.go:212 +0x3f
entgo.io/ent/entc/gen.GenerateFunc.Generate(0x18a9898?, 0xc000500510?)
	/Users/<>/go/pkg/mod/entgo.io/ent@v0.11.3-0.20220830071904-3b1b75b9d7a9/entc/gen/graph.go:139 +0x1f
entgo.io/contrib/entgql.removeOldAssets.func1(0x20?)
	/Users/<>/go/pkg/mod/entgo.io/contrib@v0.3.2/entgql/template.go:608 +0x97
entgo.io/ent/entc/gen.GenerateFunc.Generate(0xc000680000?, 0xc0011d2be0?)
	/Users/<>/go/pkg/mod/entgo.io/ent@v0.11.3-0.20220830071904-3b1b75b9d7a9/entc/gen/graph.go:139 +0x1f
entgo.io/contrib/entgql.(*Extension).genSchemaHook.func1.1(0x18a4b00?)
	/Users/<>/go/pkg/mod/entgo.io/contrib@v0.3.2/entgql/extension.go:218 +0x3a
entgo.io/ent/entc/gen.GenerateFunc.Generate(0x18a4b00?, 0xc00115a840?)
	/Users/<>/go/pkg/mod/entgo.io/ent@v0.11.3-0.20220830071904-3b1b75b9d7a9/entc/gen/graph.go:139 +0x1f
entgo.io/ent/entc/gen.(*Graph).Gen(0xc00077ac80)
	/Users/<>/go/pkg/mod/entgo.io/ent@v0.11.3-0.20220830071904-3b1b75b9d7a9/entc/gen/graph.go:203 +0x96
entgo.io/ent/entc.generate({0x173900e, 0xc}, 0xa0?)
	/Users/<>/go/pkg/mod/entgo.io/ent@v0.11.3-0.20220830071904-3b1b75b9d7a9/entc/entc.go:375 +0x92
entgo.io/ent/entc.Generate({0x173900e, 0xc}, 0xc0001ac3c0, {0xc000187f20, 0x1, 0xc0000021a0?})
	/Users/<>/go/pkg/mod/entgo.io/ent@v0.11.3-0.20220830071904-3b1b75b9d7a9/entc/entc.go:86 +0x21f
main.main()
	/Users/<>/go/src/com.<>/<>/ent/entc.go:24 +0x19c
exit status 2
```

> cmd 
```sh
go run -mod=mod entgo.io/ent/cmd/ent generate ./ent/schema
```

> output
```
panic: template: setter.tmpl:69: unexpected " " in in {{continue}}

goroutine 1 [running]:
entgo.io/ent/entc/gen.MustParse(...)
	/Users/<>/go/pkg/mod/entgo.io/ent@v0.11.3-0.20220830071904-3b1b75b9d7a9/entc/gen/template.go:341
entgo.io/ent/entc/gen.initTemplates()
	/Users/<>/go/pkg/mod/entgo.io/ent@v0.11.3-0.20220830071904-3b1b75b9d7a9/entc/gen/template.go:227 +0x73b
entgo.io/ent/entc/gen.(*Graph).templates(0xc0013b62c0)
	/Users/ke<>nnedy/go/pkg/mod/entgo.io/ent@v0.11.3-0.20220830071904-3b1b75b9d7a9/entc/gen/graph.go:791 +0x36
entgo.io/ent/entc/gen.generate(0xc0013b62c0)
	/Users/<>/go/pkg/mod/entgo.io/ent@v0.11.3-0.20220830071904-3b1b75b9d7a9/entc/gen/graph.go:212 +0x3f
entgo.io/ent/entc/gen.GenerateFunc.Generate(0x27?, 0x40?)
	/Users/<>/go/pkg/mod/entgo.io/ent@v0.11.3-0.20220830071904-3b1b75b9d7a9/entc/gen/graph.go:139 +0x1f
entgo.io/ent/entc/gen.(*Graph).Gen(0xc0013b62c0)
	/Users/<>/go/pkg/mod/entgo.io/ent@v0.11.3-0.20220830071904-3b1b75b9d7a9/entc/gen/graph.go:203 +0x96
entgo.io/ent/entc.generate({0x7ff7bfeff5b2, 0xc}, 0x50?)
	/Users/<>/go/pkg/mod/entgo.io/ent@v0.11.3-0.20220830071904-3b1b75b9d7a9/entc/entc.go:375 +0x92
entgo.io/ent/entc.Generate({0x7ff7bfeff5b2, 0xc}, 0xc000215220, {0xc000365d40, 0x2, 0x0?})
	/Users/<>/go/pkg/mod/entgo.io/ent@v0.11.3-0.20220830071904-3b1b75b9d7a9/entc/entc.go:86 +0x21f
entgo.io/ent/cmd/internal/base.GenerateCmd.func1(0xc000422c80?, {0xc00006ed40, 0x1, 0x1?})
	/Users/<>/go/pkg/mod/entgo.io/ent@v0.11.3-0.20220830071904-3b1b75b9d7a9/cmd/internal/base/base.go:174 +0x2af
github.com/spf13/cobra.(*Command).execute(0xc000422c80, {0xc00006ed20, 0x1, 0x1})
	/Users/<>/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0xc000422500)
	/Users/<>/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/<>/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
	/Users/<>/go/pkg/mod/entgo.io/ent@v0.11.3-0.20220830071904-3b1b75b9d7a9/cmd/ent/ent.go:23 +0xb0
exit status 2
```

## Expected Behavior 🤔

Schema should be regenerated without issues

## Steps to Reproduce 🕹

[TheBeachmaster/ent-bug-2938](https://github.com/TheBeachMaster/ent-bug-2938)

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.18.1  |
| Ent         | 0.11.3-0.20220830071904-3b1b75b9d7a9   |
| Database    | Postgres   |
| Driver      | github.com/jackc/pgx/v4 v4.17.2       |

**Comment by TheBeachMaster** [comment] 2022-09-18 15:34
Downgrading to `v0.11.2` solves the issue. 

Maybe I should avoid  installing bleeding edge packages

**Comment by a8m** [comment] 2022-09-20 12:12
Hey @TheBeachMaster! What Go version do you use? Ent supports the last two Go versions (1.18, 1.19) and it looks like your codegen fails because the template uses the `{{continue}}` command in the template, that was added in Go 1.18.

**Comment by TheBeachMaster** [comment] 2022-09-20 18:01
Hello @a8m  I'm on go `1.18.1`

**Comment by a8m** [comment] 2022-09-20 18:03
Can you please share with us a reproducible example using https://github.com/ent/bug?

**Comment by TheBeachMaster** [comment] 2022-09-20 18:04
Alright ...

**Comment by a8m** [comment] 2022-09-20 18:05
Thanks 🙏🏻

**Comment by a8m** [comment] 2022-09-21 20:12
Hey @TheBeachMaster, any update on this?

**Comment by TheBeachMaster** [comment] 2022-09-22 22:25
Hello @a8m apologies for the late response.

The repo is at https://github.com/TheBeachMaster/ent-bug-2938

You can reproduce it by running `go generate ./...` or `go run -mod=mod entgoi.io/ent/cmd/ent generate ./ent/schema`

**Comment by a8m** [comment] 2022-09-26 10:28
Hey! I just tested it and it works without any issues on my machine and also on GitHub workspaces:

```text
@a8m ➜ /workspaces/ent-bug-2938 (master) $ go generate ./...
go: downloading entgo.io/ent v0.11.3-0.20220915211011-0adfb94c30c7
go: downloading github.com/go-openapi/inflect v0.19.0
go: downloading github.com/spf13/cobra v1.5.0
go: downloading golang.org/x/tools v0.1.13-0.20220804200503-81c7dc4e4efa
go: downloading github.com/olekukonko/tablewriter v0.0.5
go: downloading ariga.io/atlas v0.7.1-0.20220916052807-995212d7e7e9
go: downloading github.com/mattn/go-runewidth v0.0.9
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/google/uuid v1.3.0
go: downloading github.com/hashicorp/hcl/v2 v2.13.0
go: downloading github.com/zclconf/go-cty v1.8.0
go: downloading golang.org/x/mod v0.6.0-dev.0.20220419223038-86c51ed26bb4
go: downloading github.com/agext/levenshtein v1.2.1
go: downloading github.com/apparentlymart/go-textseg/v13 v13.0.0
go: downloading github.com/mitchellh/go-wordwrap v0.0.0-20150314170334-ad45545899c7
go: downloading github.com/google/go-cmp v0.5.6
go: downloading golang.org/x/text v0.3.7
go: downloading golang.org/x/sys v0.0.0-20220722155257-8c9f86f7a55f

@a8m ➜ /workspaces/ent-bug-2938 (master) $ go test ./...
?       entgo.io/bug/ent        [no test files]
?       entgo.io/bug/ent/enttest        [no test files]
?       entgo.io/bug/ent/hook   [no test files]
?       entgo.io/bug/ent/migrate        [no test files]
?       entgo.io/bug/ent/predicate      [no test files]
?       entgo.io/bug/ent/runtime        [no test files]
?       entgo.io/bug/ent/schema [no test files]
?       entgo.io/bug/ent/user   [no test files]
```

Closing for now, but please reopen if you're able to reproduce this. I'm also available for any questions on our [Discord server](https://discord.gg/qZmPgTE6RX). Thanks 🙏

**Closed by a8m** 2022-09-26 10:28 UTC

**Comment by giautm** [comment] 2022-09-26 18:12
Hello @TheBeachMaster we found the issue with space after the `continue` keyword in Go 1.18. So, We update our template to backward compatible with go 1.18. You can see the below issue for more detail. Happy coding!

https://github.com/golang/go/issues/51670
