### ISSUE TITLE
 multi field DISTINCT do not work

### ISSUE THREAD

**Issue by feeops** [ent/ent#2238] opened 2021-12-28 03:30 UTC
Core code

```
type t struct {
	RegionId    string `sql:"region_id"`
	Category    string `sql:"category"`
	StorageType string `sql:"storage_type"`
}

db := database.InitDB()
var ns []t
err := db.Debug().RDSPrice.Query().Unique(true).Select(
rdsprice.FieldRegionId, rdsprice.FieldCategory, rdsprice.FieldStorageType).Scan(context.Background(), &ns)
fmt.Println(err)
```

debug sql is
```
driver.Query: query=SELECT `aliyun_rds_price`.`region_
id`, `aliyun_rds_price`.`category`, `aliyun_rds_price`.`storage_type` FROM
 `aliyun_rds_price` args=[]
```

lost DISTINCT word

**Comment by a8m** [comment] 2021-12-28 08:02
Hey @feeops 👋 
What version of ent do you use? Can you please try this on the latest master? `go get entgo.io/ent@master` and re-run codegen.

**Comment by feeops** [comment] 2021-12-28 09:43
@a8m I use release v0.9.1

**Comment by feeops** [comment] 2021-12-28 09:51
@a8m I test entgo.io/ent v0.9.2-0.20211225130249-deb63d02927b
It do not work

**Comment by a8m** [comment] 2021-12-28 09:58
Can you please upload a reproducible example with https://github.com/ent/bug, so I can test it? Thanks.

I don't want to bother you, but I'm not able to reproduce this. I just checked it locally:
```go
client.Debug().User.Query().Unique(true).Select(user.FieldName, user.FieldAge).Scan(ctx, &v)
// SELECT DISTINCT `users`.`name`, `users`.`age` FROM `users`
```

**Comment by feeops** [comment] 2021-12-28 11:18
@a8m 

It works now

```
go get -u entgo.io/ent@master
go generate ./ent
```

Then run the code.Thanks a lot

**Comment by a8m** [comment] 2021-12-28 14:38
Great, can we close this issue?

**Closed** 2021-12-29 02:25 UTC
