### ISSUE TITLE
How to update multiple tables with a single query?

### ISSUE THREAD

**Issue by shaswa** [ent/ent#2557] opened 2022-05-21 23:28 UTC
Is it possible to update multiple tables with a single query using ent? 

Example query:

```
UPDATE users u, pets p 
SET u.removed_at = CURRENT_TIMESTAMP, 
  p.removed_at = CURRENT_TIMESTAMP
WHERE p.owner_id = u.id
AND u.id = 1
;
```

Ent Schemas
```
type User struct {
  ent.Schema
}

func (User) Fields() []ent.Field {
  return []ent.Field{
     field.Uint64("id").
     field.Time("removed_at").
  }
}

func (User) Edges() []ent.Edge {
  return []ent.Edge{
    edge.From("pets", Pet.Type).Ref("owner"),
  }
}


type Pet struct {
  ent.Schema
}

func (Pet) Fields() []ent.Field {
  return []ent.Field{
     field.Uint64("id").
     field.Uint64("owner_id").
     field.Time("removed_at").
  }
}

func (Pet) Edges() []ent.Edge {
  return []ent.Edge{
    edge.To("owner", User.Type).Field("owner_id"),
  }
}


```

**Comment by a8m** [comment] 2022-05-25 09:58
Hey @shaswa 👋 

This feature is not supported currently in Ent but it can be a really nice addition. Please, feel free to propose an API for this. 

Also, I think we can merge this issue with https://github.com/ent/ent/issues/1815, thoughts?

**Comment by a8m** [comment] 2023-05-15 10:42
Hey! Closing, as this is a duplicate of #1815. 

Just to update you that we have an internal implementation for BulkUpdate that we might be able to open-source soon. Thanks for suggesting this 🙏

**Closed by a8m** 2023-05-15 10:42 UTC
