### ISSUE TITLE
After updating the ent version from v0.10.2 to v0.11.3, the enttest migration stopped working. (SQLITE3, memory)

### ISSUE THREAD

**Issue by sea-edge** [ent/ent#3024] opened 2022-10-20 09:31 UTC
After updating the ent version from v0.10.2-0.20220502113020-4ac82f5bb3f0 to v0.11.3, the enttest migration stopped working. (SQLITE3, memory)

The error is.
`enttest.go:63: sql/schema: set sequence for "xxxx" table: no such table: sqlite_sequence
`
go version 1.19

```go
func TestXXX(t *testing.T) {
    opts := []enttest.Option{
        enttest.WithOptions(ent.Log(t.Log)),
        enttest.WithMigrateOptions(migrate.WithGlobalUniqueID(true)),
    }
    client := enttest.Open(t, "sqlite3", "file:ent?mode=memory&cache=shared&_fk=1", opts...)
    defer client.Close()
    // ...
}
```

Is there a solution?

**Comment by a8m** [comment] 2022-10-20 09:38
Thanks for reporting this, @sea-edge. What is your SQLite version?

**Comment by sea-edge** [comment] 2022-10-20 09:45
github.com/mattn/go-sqlite3 v1.14.15

**Comment by sea-edge** [comment] 2022-10-20 09:47
@a8m 
Thanks for the reply.

**Comment by sea-edge** [comment] 2022-10-20 12:42
@a8m 
We have created a simple test code for you to check.
Thank you in advance.

https://github.com/sea-edge/ent/tree/question/ent_issue_3024

```shell
$ cd examples/start/
$ go test $(go list ./... | grep -v -e /ent -e docs -e mock -e /cmd) -cover
--- FAIL: Test_main (0.00s)
    enttest.go:85: sql/schema: set sequence for "hoge_administrators" table: no such table: sqlite_sequence
FAIL
coverage: [no statements]
exit status 1
FAIL    entgo.io/ent/examples/start     0.025s
```

**Comment by sea-edge** [comment] 2022-10-20 13:32
@a8m 
A small reproduction code was created based on the template.
https://github.com/sea-edge/ent-issue-3024

**Comment by a8m** [comment] 2022-10-20 21:46
Hey! Thanks for the example repository. It helped me to reproduce this issue quickly.

I found the issue, and you need to remove the following line from the migration options because the `GlobalUniqueID` option generates integer IDs with a specific range on the table creation/modification, and your schema defines `ulid`/`string` based IDs. In SQLite, it's called sequence, and that's why you get this error. Read more about it here: https://entgo.io/docs/migrate#universal-ids.

```diff
- enttest.WithMigrateOptions(migrate.WithGlobalUniqueID(true)),
```

I'll keep this issue open and add validation for this use case tomorrow. Thanks again 🙏

**Comment by sea-edge** [comment] 2022-10-21 02:19
@a8m 
Thank you very much.
I am waiting for a resolution.

**Comment by a8m** [comment] 2022-10-21 06:30
> I'll keep this issue open and add validation for this use case tomorrow. Thanks again 🙏

OK, I verified with some of my internal tests, and it looks like we can't reject the `WithGlobalUniqueID` option when text IDs are used because there are situations of IDs with mixed types. 

In your case, I'll suggest just removing this option, and I'll change the issue title so other readers can benefit from this in the future.  

Closing, but please feel free to reopen if you still need help or join our [Discord community](https://discord.gg/qZmPgTE6RX).

**Closed by a8m** 2022-10-21 06:30 UTC

**Comment by mrcleanandfresh** [comment] 2023-12-29 19:10
For future people: I had the same issue, but it wasn't about the sequence. The error simply stated the table didn't exist. Even though I verified that the `enttest` auto-migration was running. I had copy/pasted the string [from the docs](https://entgo.io/docs/testing/):
```golang
func TestXXX(t *testing.T) {
    client := enttest.Open(t, "sqlite3", "file:ent?mode=memory&_fk=1")
    defer client.Close()
    // ...
}
```
Turns out I needed it needed a subtle change:
```diff
func TestXXX(t *testing.T) {
-  client := enttest.Open(t, "sqlite3", "file:ent?mode=memory&_fk=1")
+  client := enttest.Open(t, "sqlite3", "file:ent?mode=memory&cache=shared&_fk=1")
    defer client.Close()
    // ...
}
```
I'd be interesting in hearing an explanation (maybe from @a8m), but it's not needed. Ultimately, I wanted to leave this here for Googlers, since it's related in a subtle way.

Thanks for a great library! I've been using it like crazy and love it, fantastic work, keep it up.

**Comment by Jubilee101** [comment] 2024-03-21 19:54
Thank you @mrcleanandfresh for saving my day!

**Comment by joshhe** [comment] 2024-05-09 19:49
@mrcleanandfresh you saved my day as well!! Thanks!

**Comment by joshhe** [comment] 2024-05-10 02:24
In case any body else is running into no such table error. See this doc:
https://github.com/mattn/go-sqlite3/blob/master/README.md#faq
I changed to use "cache=shared", but some of tests were still not working if I run all of them together. Each one of them opens a new ent test client.  I have to do the following to make it work. 
`
	file := uuid.NewString()
	dataSource := fmt.Sprintf("file:%s?mode=memory&cache=shared&_fk=1", file)
	client := enttest.Open(t, "sqlite3", dataSource)`

**Comment by sarinarw** [comment] 2024-09-30 18:20
Adding `cache=shared` also fixed this "no such table" error for me. Thanks @mrcleanandfresh !
