### ISSUE TITLE
SchemaConfig To Define Table Schema Is Ignored When Used With Annotations To Set Custom Table Name

### ISSUE THREAD

**Issue by qgervacio** [ent/ent#1917] opened 2021-09-05 15:10 UTC
My `sch.post` table is in different schema thus i had to use `--feature sql/schemaconfig`

```
dbc, err := codegen.Open(
	"postgres",
	<conn-string>,
	codegen.AlternateSchema(codegen.SchemaConfig{
		Post: "sch",
	}))
```

On generation, `ent` opted to generate a plural (can this be disabled?) form name of the table. My table name becomes `sch.posts` thus I get ` pq: relation \"sch.posts\" does not exist` error

Now I had to use `Annotations` to specify the **original** table name. 

```
func (Post) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "post"}, // fails to generate if sch.post
	}
}
```

But by doing so, `SchemaConfig` seems to be ignored? Now i get the error `codegen: post not found`

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

`SchemaConfig` defined is ignored when used with `Annotations`. Table access is now `post`

## Expected Behavior 🤔

`SchemaConfig` + `Annotations` should result to `sch.post`

## Steps to Reproduce 🕹

Steps:

1. Create a table with a singular name (ex. post) in a different schema.
2. Use `SchemaConfig` to configure the table schema (ex. `sch`). Results to `sch.posts`. You'll  get `does not exist` error.
3. Use `Annotations` to configure custom table name. Results to `post`. You'll get `not found` error.

## Your Environment 🌎

| Tech           | Version |
| ----------- | ------- |
| Go          | 1.17  |
| Ent         | v0.9.1   |
| Database    | Postgres (postgres:13.3-alpine) |
| Driver      | github.com/lib/pq        |

**Comment by a8m** [comment] 2021-09-07 13:24
Hey @qgervacio and thanks for opening this issue.

I'm not able to reproduce this issue. Can you please create an example repository (with docker-compose) that reproduces this bug and post it here? Thanks 🙏

**Comment by a8m** [comment] 2021-09-24 11:23
Closing as I'm not able to reproduce this issue and it looks like things work as expected. 

@qgervacio, please reopen this issue if you still have troubles with the `SchemaConfig` feature 🙏

**Closed by a8m** 2021-09-24 11:23 UTC
