### ISSUE TITLE
goroutine in transaction 

### ISSUE THREAD

**Issue by guihouchang** [ent/ent#3423] opened 2023-03-30 07:45 UTC
An error occurred when I used goroutine in a transaction. The following is my code
```
func (r *RestUsecase) TestGoroutineInTx(ctx context.Context) error {
	return r.tx.InTx(ctx, func(ctx context.Context) error {
		eg := errgroup.WithCancel(ctx)
		eg.Go(func(ctx context.Context) error {
			_ = r.Create(ctx, "aaa", "bbb", "cccc")
			return nil
		})

		eg.Go(func(ctx context.Context) error {
			_ = r.Create(ctx, "aaa", "bbb", "cccc")
			return nil
		})

		eg.Go(func(ctx context.Context) error {
			_ = r.Create(ctx, "aaa", "bbb", "cccc")
			return nil
		})

		eg.Go(func(ctx context.Context) error {
			_ = r.Create(ctx, "aaa", "bbb", "cccc")
			return nil
		})

		return eg.Wait()
	})
```
get error:committing transaction: invalid connection

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19.1  |
| Ent         | v0.11.7   |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by crossworth** [comment] 2023-04-07 21:38
Hi @guihouchang, if you are getting `invalid connection`, I'm pretty sure that the connection was released, it's hard to say why, but looking at your code I think we can hint at a few things.

- Maybe the transaction was commited/rollbacked before all the goroutines executed
- Maybe the context was canceled and some long running goroutine could not be canceled (a goroutine that can not be canceled in the first place, goroutine with tight loops or that dont check the context for example)

Now I would like to ask why are you using goroutines inside a transaction?

[`sql.DB`](https://pkg.go.dev/database/sql#DB) states `Once DB.Begin is called, the returned Tx is bound to a single connection.`, if you are using long running queries, that are just waiting for to the database to complete and return, adding new goroutines will not improve the speed as you imagine (some speed could be observed in theory, but if the problem is the query time, I think it will not be noticeable).

I would argue that using goroutines like in this example creates new problems, like now you don't really have control on the order of execution, can not have queries that depends on each other results without some kind of synchronization or have queries that changes/query the same data.

If you want to improve the speed, there are a few things you can do:
- [Batch/Bulk insert](https://entgo.io/docs/crud/#create-many)
- Change database settings
- Play with transaction isolation levels
- Use more transactions

**Comment by guihouchang** [comment] 2023-04-10 03:02
Thank you for your suggestion. @crossworth

**Comment by a8m** [comment] 2023-04-10 11:45
Thank you for the comprehensive explanation, @crossworth. 

@guihouchang - As Pedro mentioned earlier, a transaction is tied to a single connection, and since you cannot execute multiple statements in parallel using one connection, you'll encounter either "busy buffer" or "invalid/bad connection" errors.


Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎

**Closed by a8m** 2023-04-10 11:45 UTC
