### ISSUE TITLE
Deep Nested Edge Queries

### ISSUE THREAD

**Issue by sneakywombat** [ent/ent#1574] opened 2021-05-18 19:47 UTC
I have a question about querying for a deeply nested edge.  Assume the following:

` 

    // Network entity schema.
    type Network struct {
        ent.Schema
    }

    // Fields of Network
    func (Network) Fields() []ent.Field {
        return []ent.Field{
            field.String("name")
        }
    }

    // Edges of the Network.
    func (Network) Edges() []ent.Edge {
        return []ent.Edge{
            edge.To("addresses", Address.Type),
            edge.To("inherits", Network.Type).
                From("inherited_by"),
        }
    }

    // Address entity schema.
    type Address struct {
        ent.Schema
    }

    // Fields of Address
    func (Address) Fields() []ent.Field {
        return []ent.Field{
            field.String("prefix").
                MaxLen(150).
                NotEmpty().
                Comment("eg 1.1.1.1/32"),
            field.Bytes("network").
                GoType(net.IP("127.0.0.1")).
                Comment("network address of the given network"),
            field.Bytes("broadcast").
                GoType(net.IP("127.0.0.1")).
                Comment("broadcast address of the given network"),
        }
    }

    // Edges of the Address.
    func (Address) Edges() []ent.Edge {
        return []ent.Edge{
            edge.From("networks", Network.Type).
                Ref("addresses"),
        }
    }
`

Networks can have addresses and also inherit from other networks.  Since this inheritance can occur several times, I'm having a hard time writing a single query to obtain the results from deeply associated networks.  So far, I've only been able to write multiple queries that then merge data together to produce a result.  I was wondering if it was possible to optimize this down to one?

Lets say we have the following:

`

	addr1, err := client.Address.Create().
		SetPrefix("10.0.0.10/24").
		SetNetwork(net.ParseIP("10.0.0.0")).
		SetBroadcast(net.ParseIP("10.0.0.255")).
		Save(ctx)

	addr2, err := client.Address.Create().
		SetPrefix("10.0.1.10/24").
		SetNetwork(net.ParseIP("10.0.1.0")).
		SetBroadcast(net.ParseIP("10.0.1.255")).
		Save(ctx)

	network1, err := client.Network.Create().
		SetName("TEST_NETWORK1").
		AddAddresses(addr1).
		Save(ctx)

	network2, err := client.Network.Create().
		SetName("TEST_NETWORK2").
		AddAddresses(addr2).
                AddInheritedBy(network1).
		Save(ctx)
	require.NoError(t, err)
`

If i wanted to find addr2:

`

    ip, _, _ := net.ParseCIDR("10.0.1.10/24")
    matches, err := client.Network.Query().
    Where(
        network.HasAddressesWith(
            address.NetworkLTE(ip.Network()),
            address.BroadcastGTE(ip.Broadcast()),
        ),
    )`

This doesn't produce results. however, it will produce results for the first ent if it has such an address condition.  Any association more than one edge away from the starting network does not seem to get queried.  I'm either querying it wrong or it's not supported, or something else.  haha.  Any suggestions would be awesome. thanks for making such an amazing project!

**Comment by rotemtam** [comment] 2021-05-19 10:02
Hi @sneakywombat ,
Thanks for reaching out I think this is a duplicate of https://github.com/ent/ent/issues/1024.
As far as I know, recursive traversal is currently not supported, but please join the discussion on that issue.

Also, Feel free to subscribe to our [newsletter](https://www.getrevue.co/profile/ent) to get more updates and information about the project in the future!

Closing, please re-open if I'm mistaken.

**Closed** 2021-05-19 10:02 UTC

**Comment by a8m** [comment] 2021-05-19 10:50
Hey @sneakywombat! It's great to hear from you again 😃
Can you please join the Ent [Slack channel](https://gophers.slack.com/archives/C01FMSQDT53) and ping me there? 

Not sure why your last query doesn't return any result, because you're not querying the `inherited_by` relation at all. 

> Any association more than one edge away from the starting network does not seem to get queried

As Rotem mentioned, recursive traversals are not supported atm, but you can do it manually and control the level of depth as follows:

```go
ip, _, _ := net.ParseCIDR("10.0.1.10/24")
matches, err := client.Network.Query().
	Where(
		network.Or(
			// Level 1.
			network.HasAddressesWith(
				address.NetworkLTE(ip.Network()),
				address.BroadcastGTE(ip.Broadcast()),
			),
			// Level 2.
			network.HasInheritedByWith(
				network.HasAddressesWith(
					address.NetworkLTE(ip.Network()),
					address.BroadcastGTE(ip.Broadcast()),
				),
			),
			// Level 3.
			// ...
		),
	)
```

If you have too many predicates, you can create this dynamically.

**Comment by a8m** [comment] 2021-05-20 10:51
> Hey @a8m! i'd love to join the slack channel, it won't let me in though. Can i get an invite?

Sure, @rotemtam created a guide on how to connect to our Slack channel. Please see https://entgo.io/docs/slack

Please ping me after joining the channel, and of course, tag me here if you still have trouble with it.

**Comment by a8m** [comment] 2021-05-25 17:42
Hey @sneakywombat, this example should solve your problem - https://github.com/ent/ent/pull/1599

We'll add documentation for it later this week.

**Comment by sneakywombat** [comment] 2021-05-25 18:00
Nice! sql.WithRecursive.  I was wondering if that was an option.  I'll give this a shot. thanks!
