### ISSUE TITLE
entgo and GraphQL

### ISSUE THREAD

**Issue by thelark** [ent/ent#1778] opened 2021-07-28 07:43 UTC
I want to implement the following function,
i have a query like 
```gql
query GetUser {
  users {
    id
    name
    friends(first: 10, after: "opaqueCursor") {
      edges {
        cursor
        node {
          id
          name
        }
      }
      pageInfo {
        hasNextPage
      }
    }
  }
}
```
how to define schema?

**Comment by a8m** [comment] 2021-07-28 09:58
Hey @thelark and thanks for opening this issue.

Nested pagination is not supported atm by `entgql`, and you'll need to implement this manually in your resolver (See the `forceResolver` option in [our website](https://entgo.io/docs/graphql/#usage-and-configuration)).

Closing as this is a duplicate of https://github.com/ent/ent/issues/1180, so let's continue the discussion there or on our [Slack channel](https://entgo.io/docs/slack/). 

Thanks 🙏

**Closed by a8m** 2021-07-28 09:58 UTC
