### ISSUE TITLE
Backward Incompatibility for Migration from v0.8.0 to v0.11.0

### ISSUE THREAD

**Issue by miladibra10** [ent/ent#2908] opened 2022-09-07 06:21 UTC
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

I'm using v0.8.0 of ent in my project. I wanted to upgrade it to v0.11.0. I updated the library via go mod and re-generated all needed files from schema. But I face an error when calling the `Migrate` function on a database that is already migrated with the v0.8.0 version of ent.

The error is like this:
```
Could not run migrations: could not migrate schema to db: sql/schema: changing "<TABLE_NAME>" table primary key is not supported
```

I checked between two version. `Key` field's value in table object in v0.11.0 version is `PRI` but the value in v0.8.0 version is an empty string.

> Note: There are other backward compatibility issues with v0.10.0 and v0.10.1 version but it works fine with v0.9.1

## Expected Behavior 🤔

I think migration should work without any errors!

## Steps to Reproduce 🕹

Steps:

1. install v0.8.0 version of ent
2. create an schema and generate needed files
3. run migration on a database (PostgreSQL in my case)
4. upgrade ent version to v0.11.0
5. regenerate needed files
6. run migration on the same database that was used for step 3 before.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17  |
| Ent         | 0.11.0   |
| Database    | PostgreSQL   |
| Driver      | https://github.com/jackc/pgx/v4 (v4.6.1-0.20200606145419-4e5062306904)       |

**Comment by a8m** [comment] 2022-09-07 06:33
Hey @miladibra10 and thanks for raising this issue.
Can you please create an example to reproduce this using [ent/bug](https://github.com/ent/bug)?

**Comment by a8m** [comment] 2022-09-08 07:09
Closing due to no feedback. Please, reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) if you still need help with this.

**Closed by a8m** 2022-09-08 07:09 UTC
