### ISSUE TITLE
After Running Auto Migrations, Create crashes with segmentation violation

### ISSUE THREAD

**Issue by Darren-Fuerst** [ent/ent#2808] opened 2022-07-28 06:13 UTC
Hello, 

So as in the title my programm crashes after succesfully running the auto migration as per docs. 

I tried it with both pq and pgx as drivers. Same Behaviour.

Here is the db after the migrations:

![image](https://user-images.githubusercontent.com/77537563/181432214-b7943b78-320e-4b26-ace8-f6fc12222922.png)

I believe there is one table too much that is not needed and I can not always find the Foreign Key Fields so I must have messed up in the schemas somewhere but I can't figure it out completely.

Here are my Schema files and after those I'll post main.go. 
---------
handout.go 
```

// Fields of the Handout.
func (Handout) Fields() []ent.Field {
	return []ent.Field{
		field.Time("handed_out_at").Default(time.Now()),
		field.Int("admin_id"),
		field.Int("customer_id"),
		field.Int("order_id").Optional().Nillable(),
		field.Bool("expiration_cleanup").Default(false),
		field.Text("comment").Optional().Nillable(),
		field.Float("price").Optional().Nillable().Positive(),
	}
}

// Edges of the Handout.
func (Handout) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("item", Item.Type).Required().Through("handout_items", Handoutitem.Type),
		edge.To("admin", User.Type),
		edge.To("customer", User.Type),
		edge.To("purchase", Purchase.Type),
	}
```
-------

handoutitem.go

```

func (Handoutitem) Annotations() []schema.Annotation {
	return []schema.Annotation{
		field.ID("handout_id", "item_id"),
	}
}

// Fields of the Handoutitem.
func (Handoutitem) Fields() []ent.Field {
	return []ent.Field{
		field.Int("handout_id"),
		field.Int("item_id"),
		field.Int("amount").Positive(),
		field.Float("price").Optional().Nillable().Positive(),
	}
}

// Edges of the Handoutitem.
func (Handoutitem) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("handout", Handout.Type).
			Unique().
			Required().
			Field("handout_id"),
		edge.To("item", Item.Type).
			Unique().
			Required().
			Field("item_id"),
	}
```
--------------
item.go
```

// Fields of the Item.
func (Item) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").NotEmpty(),
		field.Int("amount_in_stock").Positive(),
		field.Int("wanted_stock").Positive(),
		field.Int("total_delivered").Positive().Default(0),
		field.Bool("is_available_for_order").Default(true),
	}
}

// Edges of the Item.
func (Item) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("purchase", Purchase.Type).
			Ref("item").
			Through("purchased_item", Purchaseditem.Type),
		edge.From("handout", Handout.Type).
			Ref("item").
			Through("handout_items", Handoutitem.Type),
	}
```

-------
purchase.go

```

// Fields of the Purchase.
func (Purchase) Fields() []ent.Field {
	return []ent.Field{
		field.Time("purchased_at").Default(time.Now()),
		field.Bool("is_in_working").Default(false),
		field.Text("comment").Optional().Nillable(),
		field.Bool("is_closed").Default(false),
		field.Bool("is_deleted").Default(false),
		field.Int("user_id"), // should be foreign key defined as edge to customer
	}
}

// Edges of the Purchase.
func (Purchase) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("customer", User.Type).Required(),
		edge.To("item", Item.Type).Required().Through("purchased_items", Purchaseditem.Type),
		edge.From("handout", Handout.Type).
			Ref("purchase").Unique(),
	}
```
------------
purchaseditem.go

```

// Fields of the Purchase.
func (Purchase) Fields() []ent.Field {
	return []ent.Field{
		field.Time("purchased_at").Default(time.Now()),
		field.Bool("is_in_working").Default(false),
		field.Text("comment").Optional().Nillable(),
		field.Bool("is_closed").Default(false),
		field.Bool("is_deleted").Default(false),
		field.Int("user_id"), // should be foreign key defined as edge to customer
	}
}

// Edges of the Purchase.
func (Purchase) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("customer", User.Type).Required(),
		edge.To("item", Item.Type).Required().Through("purchased_items", Purchaseditem.Type),
		edge.From("handout", Handout.Type).
			Ref("purchase").Unique(),
	}
```
----------------
role.go

```

// Fields of the Role.
func (Role) Fields() []ent.Field {
	return []ent.Field{
		field.Enum("role").Values("ADMIN", "USER"),
	}
}

// Edges of the Role.
func (Role) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("user", User.Type).
			Ref("role").Unique(),
	}
}

func (Role) Indexes() []ent.Index {
	return []ent.Index{
		// non-unique index.
		index.Fields("role").Unique(),
	}
```

---------------

user.go

```

// Fields of the User.
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.String("organisation").NotEmpty().Immutable(),
		field.String("email").NotEmpty().Unique(),
		field.String("password").NotEmpty(),
		field.String("firstname").NotEmpty(),
		field.String("lastname").NotEmpty(),
		field.Int("roleid"),
		field.String("telephone").Optional().Nillable(),
		field.Bool("isblocked").Default(false).Comment("Lets Admins block Users from Ordering"),
		field.Time("created_at").Default(time.Now()).Immutable(),
		field.Time("last_login").Optional().Nillable(),
	}

}

// Edges of the User.
func (User) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("role", Role.Type).Required(),
		edge.From("purchase", Purchase.Type).Ref("customer"),
		edge.From("handout_admin", Handout.Type).Ref("admin").Unique(),
		edge.From("handout_customer", Handout.Type).Ref("customer").Unique(),
	}

}

// Index Fields
func (User) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("email").Unique(),
	}
```

main.go 

```
	client, err := Open(fmt.Sprintf("postgres://postgres:postgres@%v:5433/test?sslmode=disable", appConf.Database.ServiceName))
	if err != nil {
		log.Fatal(err)
	}

	defer client.Close()
	if err := client.Schema.Create(context.Background()); err != nil {
		log.Fatalf("failed creating schema resources: %v", err)
	}
	fmt.Println("Ran Migrations")

	//Up to here we are good

	// this returns <nil> , <nil>
	item, errore := client.Item. // UserClient.
					Create(). // User create builder.
					SetName("Tube").
					SetAmountInStock(10).
					SetWantedStock(5).
					Save(context.Background()) // Create and return.
	if errore != nil {
		fmt.Printf("Errore : %v\n", err)
	}

	fmt.Println(item)
```

--------------------
Console Output:

![image](https://user-images.githubusercontent.com/77537563/181433102-c5957407-0059-4776-913b-7920345fbd67.png)

I either get this error, or it prints out <nil> to the console for both variables that get returned from Create().Save()

Here is the db drawing in case it helps with the schemas:

![image](https://user-images.githubusercontent.com/77537563/181431849-c2c18c4d-1632-4d9e-9570-731141b342a2.png)

Any help is greatly appreciated

**Comment by a8m** [comment] 2022-07-28 06:19
Hey @Darren-Fuerst, and thanks for reporting this issue. It looks like it's coming from `Save` and not related to the migration.

Would you mind creating a reproducible example using [ent/bug](https://github.com/ent/bug)? I'll be able to help more quickly this way. Thanks 🙏

**Comment by Darren-Fuerst** [comment] 2022-07-28 06:49
@a8m Will do I'll try and reduce the Schema to 1-2 tables and then make a proper bug issue.

**Comment by Darren-Fuerst** [comment] 2022-07-28 10:36
@a8m Hey so I made a ent/bug repo and ran generate and it told me  that I had a field Definition messed up. I used Postive instead of NonNegative and a Default Value of 0 on that Field. 

![image](https://user-images.githubusercontent.com/77537563/181484544-d28360bd-4122-4c12-b6e7-502b39fff4d0.png)


I followed the docs during Setup so it seems, that the ent version in the bug repo is catching this issue and my Version (v.0.11.1) does not catch this. When Creating the Item?

Anyway you can have another look yourself in the bug repo I made [Bug Repo here](https://github.com/Darren-Fuerst/ent-bug-ent.Save-)

Here is the output of the ent version in the bug template if you compare it to the screenshot in my first post there is no error Message: 

![image](https://user-images.githubusercontent.com/77537563/181485280-f403551f-1023-4b33-8169-ced296a9e26c.png)

**Comment by a8m** [comment] 2022-07-28 10:51
From looking at the code, it looks like you set `total_delivered` to `0`, but you configured the field to be `Positive`. Please, set it to `NonNegative` instead.

The panic comes from line 54 because you tried to access a field of a `nil` item. In case of an error, the returned object is `nil`.

**Comment by Darren-Fuerst** [comment] 2022-07-28 10:57
@a8m  I know that now what I am trying to say is that ent v.0.11.1 does not tell you why it has the Error whereas the version from the bug Template does. After fixing that Field to be NonNegative I tried adding a User without a Required Field and it ent v.0.11.1 returned nil whereas the version in the bug report template told me "ent: missing required field "User.lastname".

**Comment by a8m** [comment] 2022-07-28 11:17
In case I'm not missing anything, it looks to me like things work as expected. This is what I did to verify it:

1\. Run your code as-is without updating ent and got:
![image](https://user-images.githubusercontent.com/7413593/181491673-810874fe-65ce-4b57-b187-4f9d0e0c6d89.png)

2\. Update ent to v0.11.1, ran codegen, and then executed your code:
![image](https://user-images.githubusercontent.com/7413593/181492004-f9e68a37-9507-49b1-bfac-8b2ffb92b5eb.png)

3\. Updated to the latest master and it also worked:
![image](https://user-images.githubusercontent.com/7413593/181492544-d819f247-c6a7-4941-96bc-85e55850ed2a.png)

**Comment by a8m** [comment] 2022-07-28 11:19
In case I'm not missing anything, it looks to me like things work as expected. This is what I did to verify it:

1\. Run your code as-is without updating ent and got:
![image](https://user-images.githubusercontent.com/7413593/181492921-9abdc176-a8fe-4150-9053-36ee4c736533.png)
2\. Update ent to v0.11.1, ran codegen, and then executed your code:
![image](https://user-images.githubusercontent.com/7413593/181492955-9d2ab02b-1c11-4b60-aff8-7b0bfa915b2d.png)
3\. Updated to the latest master and it also worked:
![image](https://user-images.githubusercontent.com/7413593/181492983-1fd0dca0-c4ad-43f4-b3a3-0c67c7d9db41.png)

**Comment by Darren-Fuerst** [comment] 2022-07-28 11:20
Hm that's weird if you want I can post my mod  but it did not show me the error in my project and only showed me the error in the bug template. 

But it seems to be an Issue in my setup then

**Comment by a8m** [comment] 2022-07-28 11:23
OK, I'm closing the issue then. If you have another example that you want one of us will give a look at, please post it here, in another issue, or in our Discord. Thanks and welcome to our community🙏

**Closed by a8m** 2022-07-28 11:23 UTC
Labels: Question
