### ISSUE TITLE
Generating schemas from the database

### ISSUE THREAD

**Issue by chenhl05** [ent/ent#1653] opened 2021-06-23 16:54 UTC
Is there a plugin that can create schemas from the database?

**Comment by rotemtam** [comment] 2021-06-23 18:51
Hi @chenhl05 
Thanks for reaching out!

Short answer: no, currently there isn't.

Medium length answer: it is easy to write plugins that generate schemas, read about it here: https://entgo.io/blog/2021/05/04/announcing-schema-imports/

Longer answer: @a8m and I are working on the infrastructure for the next release which will include a rewrite of the migration system. In that rewrite there are very good facilities for inspecting existing databases in a robust way. Once we release that, the ent schema gen plug-in will be super simple, so expected to it land a bit after the next release.

**Comment by a8m** [comment] 2021-06-23 19:33
Closing as this is a duplicate of https://github.com/ent/ent/issues/967. 

Thanks, @rotemtam and @chenhl05 😃

**Closed by a8m** 2021-06-23 19:33 UTC
