### ISSUE TITLE
How to add comments of DB?

### ISSUE THREAD

**Issue by ydx-coder** [ent/ent#2550] opened 2022-05-18 03:17 UTC
The Comment function of the schema only adds comments  in the models, it will not affect the DB

**Comment by a8m** [comment] 2022-05-18 07:34
Hey @ydx-coder and thanks for opening this issue 👋 

This feature can be simply added to Ent as Atlas is already supporting it. Please, let me know if you want to contribute this and I can support you on our [Discord server](https://discord.gg/qZmPgTE6RX). 

Closing as it's a duplicate of https://github.com/ent/ent/issues/1546.

**Closed by a8m** 2022-05-18 07:34 UTC

**Comment by a8m** [comment] 2022-12-26 15:32
The issue was resolved with: https://entgo.io/docs/schema-annotations#database-comments.

Update your Ent version to master, and check out this tweet to see an example: https://twitter.com/entgo_io/status/1607394587009589248?s=46&t=lnMIxsxQpGOTMCpsp0yPBg
