### ISSUE TITLE
Two primary keys?

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2594] opened 2022-06-01 18:39 UTC
I'm wondering if it's possible to have two Primary Keys for some tables, like:

```sql
CREATE TABLE "public"."players" (
  "id" int8 NOT NULL DEFAULT nextval('players_id_seq'::regclass),
  "tenant_id" int8 NOT NULL,
  "name" varchar COLLATE "pg_catalog"."default" NOT NULL,
  CONSTRAINT "players_pkey" PRIMARY KEY ("tenant_id", "id"),
  CONSTRAINT "players_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
)
```

I cannot find any info for this.

**Comment by a8m** [comment] 2022-06-02 16:17
Hey @frederikhors 👋 
Ent does not support composite primary keys for nodes currently (unlike [edge schemas](https://entgo.io/docs/schema-edges#edge-schema)). 

Technically, the implementation does not require significant changes in Ent because edge schemas already support it. However, I decided not to support it atm (until we'll finalize the design) because it won't play nicely with many of the integration we provide today with Ent. e.g. `entgql` - a `Node` in the graph must have an ID (it's also called ID in your tables). If users want to set up a unique constraint on two or more fields for now, they can use [index options](https://entgo.io/docs/schema-indexes#multiple-fields). 

I think we can close this as it's a duplicate of https://github.com/ent/ent/issues/400.

**Closed** 2022-06-02 16:27 UTC
