### ISSUE TITLE
entql Mutation results inconsitent with edge resulsts

### ISSUE THREAD

**Issue by idc77** [ent/ent#3190] opened 2022-12-23 14:04 UTC
Create, Update mutations return an Entity result, not a EntityEdge result
Changing signature to EntityEdge in the mutation.graphql leaves incompatible resolvers.

- [ ] The issue is present in the latest release.
- [ ] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
```gql
    createPost(input: CreatePostInput!): Post
    updatePost(id:ID!, input: UpdatePostInput!): Post
```

```go
// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input ent.CreatePostInput) (*ent.Post, error) {
	client := ent.FromContext(ctx)
	return client.Post.Create().SetInput(input).Save(ctx)
}

// UpdatePost is the resolver for the updatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, id uuid.UUID, input ent.UpdatePostInput) (*ent.Post, error) {
	client := ent.FromContext(ctx)
	return client.Post.UpdateOneID(id).SetInput(input).Save(ctx)
}
```

change it to
```
    createPost(input: CreatePostInput!): PostEdge
    updatePost(id:ID!, input: UpdatePostInput!): PostEdge
```

```go
// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input ent.CreatePostInput) (*ent.PostEdge, error) {
	client := ent.FromContext(ctx)
	return client.Post.Create().SetInput(input).Save(ctx)
}

// UpdatePost is the resolver for the updatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, id uuid.UUID, input ent.UpdatePostInput) (*ent.PostEdge, error) {
	client := ent.FromContext(ctx)
	return client.Post.UpdateOneID(id).SetInput(input).Save(ctx)
}
```

```
validation failed: packages.Load: resolvers.go:30:9: cannot use client.Post.Create().SetInput(input).Save(ctx) (value of type *"ent".Post) as *"ent".PostEdge value in return statement
resolvers.go:36:9: cannot use client.Post.UpdateOneID(id).SetInput(input).Save(ctx) (value of type *"ent".Post) as *"ent".PostEdge value in return statement
```

Why?
A graphql API is typically consumed by an apollo client in the JS world.
When you create a post, you expect the return type  of a CreatePost to be the same as the query result type, aka edge nodes.
The result then is you have to fiddle with the JS Object to have *just.the.exact.type* that is returned from CreatePost
aka
```js
    const {mutate: createPost, onDone} = useMutation(CREATE_POST,
      () => ({
        variables: {
          body: postModel.value.body
        },
        update: (cache, {data: {createPost}}) => {
          let data = cache.readQuery({query: POSTS_PAGINATED})
          let postEdge = {
            node: createPost,
            __typename: 'PostsEdge'
          }
          data = {
            ...data,
            posts: {
              totalCount: data.posts.totalCount+1,
              edges: [
                postEdge,
                ...data.posts.edges
              ],
              pageInfo: data.posts.pageInfo,
              __typename: data.posts.__typename,
            }
          }
          cache.writeQuery({query: POSTS_PAGINATED, data})
        }
      })
    )
```
this is ludicrous.
You'd have to update the object every time the query model changes.

```js
export const POSTS_PAGINATED = gql`
query postsPaginated($cursor: Cursor) {
  posts(first: 10, after: $cursor, orderBy: {direction: DESC, field:UPDATED_AT}) {
    totalCount
    edges {
      node {
        id
        createdAt
        updateTime
        sub
        body
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}`
```
What if I'd like posts with comments and profile names of posts and comments, also number of followers etc?
I'd have to manually update the whole object that is placed on top.
You might say it's not your problem. But it is your problem.
That is the single thing that's keeping me from using graphql or rather ent/gqlgen.
On one hand you have edge nodes returned from queries on the other hand you don't support edge node results.

## Expected Behavior 🤔

EntityEdge or edge node mutation results returned

## Steps to Reproduce 🕹

Steps:

1.
2.
3.
4.

## Your Environment 🌎

irrelevant

**Comment by giautm** [comment] 2022-12-23 17:12
Hello @idc77, I also faced the same problem as you a year ago. So, I open a PR to add `ToEdge` on every entity so we can convert a node to an edge. But the problem is, the edge in EntGQL require an order to generate correct ID. So, you have to pass the order of the current connection via the mutation to generate the edge. Let's take the `createPost` example.

```diff
// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input ent.CreatePostInput) (*ent.PostEdge, error) {
	client := ent.FromContext(ctx)
	p, err := client.Post.Create().SetInput(input).Save(ctx)
+	if err != nil {
+		return nil, err
+	}
+	return p.ToEdge(ent.DefaultPostOrder), nil // Use default sorting order or via the mutation argument.
}
```

**Comment by giautm** [comment] 2022-12-23 17:16
You can see more detail here. https://github.com/ent/ent/issues/1034

I will close this issue, but if something is unclear. Just let me known. I happy to help

**Closed by giautm** 2022-12-23 17:16 UTC

**Comment by a8m** [comment] 2022-12-23 17:32
Thanks for the quick support and your kindness, @giautm ❤️
