### ISSUE TITLE
Bug with custom order functions for relay connections

### ISSUE THREAD

**Issue by goingaround** [ent/ent#3220] opened 2023-01-09 08:59 UTC
Hi guys, I’m trying to configure a custom sort with a stored postgres function, and it works for me when i just query things, using the `.Order(…)` func generated for every model, but the problem is with `.Paginate(..)` generated function for querying a relay graphql connection, when i use the `.Order(…)` before the `.Paginate(…)` I’m getting an error for the count query (which is running to get the totalCount of the relay connection)

```
2022/12/07 15:03:16 driver.Query: query=SELECT COUNT("catalog_package_version"."id") FROM "catalog_package_version" WHERE "catalog_package_version"."catalog_package_id" IN (SELECT "catalog_package"."id" FROM "catalog_package" WHERE "catalog_package"."name" = $1 AND "catalog_package"."type" = $2) ORDER BY versions_sort(version) DESC args=[axios npm]
  resp: {
    "errors": [
      {
        "message": "ERROR: column \"catalog_package_version.version\" must appear in the GROUP BY clause or be used in an aggregate function (SQLSTATE 42803)",
        "path": [
          "packageVersions"
        ]
      }
    ],
    "data": null
  }
  error: packageVersions: ERROR: column "catalog_package_version.version" must appear in the GROUP BY clause or be used in an aggregate function (SQLSTATE 42803)
```
}
What I don’t get is, why would the order by be ever added to the count query?… it’s pretty redundant to order when you count

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Order by section is added to the count query
## Expected Behavior 🤔
Order by section should be excluded from the count query

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19.3  |
| Ent         | 0.11.0   |
| Database    | PostgeSQL   |
| Driver      | https://github.com/jackc/pgx     |

**Comment by khanakia** [comment] 2023-01-09 10:11
duplicate of https://github.com/ent/ent/issues/2807

**Comment by a8m** [comment] 2023-01-09 10:14
> What I don’t get is, why would the order by be ever added to the count query?… it’s pretty redundant to order when you count

I waited for your PR after our discussion on Slack 2 months ago 😅 
I'll send a patch to fix this later today. Thanks for reporting this.

**Comment by a8m** [comment] 2023-01-10 12:19
Closed with https://github.com/ent/ent/pull/3226.

**Closed by a8m** 2023-01-10 12:19 UTC
