### ISSUE TITLE
postgres: unexpected number of rows: 1 when migrate/create db on postgres 16

### ISSUE THREAD

**Issue by mimamch** [ent/ent#3752] opened 2023-09-18 15:58 UTC
- [ x] The issue is present in the latest release.
- [x ] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

its error with message:  failed creating schema resources: postgres: unexpected number of rows: 1

this only happen on postgres version 16

## Expected Behavior 🤔

Migrating successfully

## Steps to Reproduce 🕹

Steps:

1. I follwing this steps https://entgo.io/docs/getting-started#versioned-migrations
2. and run main.go that has code like this

```go
client, err := ent.Open("postgres", "host=localhost port=5432 user=postgres dbname=golang-rest password=postgres sslmode=disable")
	if err != nil {
		log.Fatalf("failed opening connection to postgres: %v", err)
	}
	defer client.Close()
	// Run the auto migration tool.
	if err := client.Schema.Create(context.Background()); err != nil {
		log.Printf("failed creating schema resources: %v", err)
	}
```

3. Error Output : 
failed creating schema resources: postgres: unexpected number of rows: 1

4. Postgres log
2023-09-18 15:38:57.072 UTC [99] STATEMENT:  CREATE TABLE `users` (
postgres  |       `id` text NOT NULL,
postgres  |       `name` text NOT NULL,
postgres  |       `email` text NOT NULL,
postgres  |       `password` text NOT NULL,
postgres  |       PRIMARY KEY (`id`)
postgres  |     );
postgres  | 2023-09-18 15:40:30.990 UTC [105] LOG:  unexpected EOF on client connection with an open transaction

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.21.1  |
| Ent         | 0.12.3   |
| Database    | PostgreSQL 16   |
| Driver      | github.com/lib/pq        |

**Comment by tjasko** [comment] 2023-09-19 19:41
I looked into this a little. This is caused by some newly introduced changes in Postgres 16, which was just released on September 14, 2023.

Previously in older versions of Postgres, when attempting to generate the SQL migrations via Ent's automated tooling, the following query would be executed & would result in something like the following. For the below example, I'm using PostgreSQL 14.2:
```
postgres=# SELECT setting FROM pg_settings WHERE name IN ('lc_collate', 'lc_ctype', 'server_version_num', 'crdb_version') ORDER BY name DESC;
  setting
------------
 140002
 en_US.utf8
 en_US.utf8
(3 rows)
```

But in Postgres 16 (using the `postgres:16` container), the above query results in the following:
```
postgres=# SELECT setting FROM pg_settings WHERE name IN ('lc_collate', 'lc_ctype', 'server_version_num', 'crdb_version') ORDER BY name DESC;
 setting
---------
 160000
(1 row)
```

This is caused by [Atlas](https://github.com/ariga/atlas), a tool used by Ent, asserting the number of returned rows in its logic:
https://github.com/ariga/atlas/blob/83ad451a4935bd10b1aa768a6c85057ef1dcb89d/sql/postgres/driver.go#L97

It appears Atlas will need to be updated first, and then a new release of Ent to support Postgres 16 fully.

**Comment by a8m** [comment] 2023-09-20 07:30
Hey @mimamch and @tjasko 👋 

The issue was resolved with https://github.com/ent/ent/pull/3751 two days ago. Upgrading to the latest version should solve the issue.

**Closed by a8m** 2023-09-20 07:30 UTC
