### ISSUE TITLE
RemovedEdges and ClearedEdges from ent.Mutation does not work

### ISSUE THREAD

**Issue by ramonmedeiros** [ent/ent#2925] opened 2022-09-12 08:07 UTC
When updating the edges of an entity, RemovedEdges and ClearedEdges does not returned updated edges.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

My goal is to listen to all updates in my ent code and create an Changelog, so I can have a history of changes.

Let's take the following example:

Car -> Manufacture

When I update a manufacture (edge of car), in the mutation object, this is the returns from the following methods:

```
(m ent.Mutation)

RemovedEdges() -> []
ClearedEdges() -> []
AddedEdges()  -> [new_manufacture_id]
```

## Expected Behavior 🤔

I was expecting to have a method to return the old edge id, in a generic way (not dealing with the entity struct). I would like to have this hook working in a generic way with all my entities, mapping the edge that was updated and return old and new values.

## Steps to Reproduce 🕹

Create two entities and add one as a edge of each other. Create a hook on it for updates and run the methods above

Steps:

1.
2.
3.
4.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19  |
| Ent         | 0.11.3   |
| Database    | Postgresql   |
| Driver      | github.com/jackc/pgx/v4       |

**Comment by a8m** [comment] 2022-09-12 09:09
Hey @ramonmedeiros and thanks for reporting this.
Do you mean that removed/cleared edges are not returned from the mutation? Can you please create a reproducible example using [`ent/bug`](https://github.com/ent/bug)?

**Comment by a8m** [comment] 2022-09-13 13:13
Closing due to no feedback and I'm not able to reproduce it. Please, reopen it if you still need help or if you can help us to reproduce it. Thanks 😃

**Closed by a8m** 2022-09-13 13:13 UTC

**Comment by ramonmedeiros** [comment] 2022-09-16 11:35
Sorry for the late reply.

Just created a minimal reproducible code here:  https://github.com/carla-se/bug

I would like to be more precise in the issue description:

`AddedEdges` works when I update the edge of an entity, but I cannot found the IDs related to it.

The hook and the test is in the `bug_test.go`

**Comment by ramonmedeiros** [comment] 2022-09-16 11:43
Thanks!
