### ISSUE TITLE
[Question] Custom ordering based on users interactions

### ISSUE THREAD

**Issue by sahmadreza** [ent/ent#3262] opened 2023-01-19 21:23 UTC
I am dealing with a huge problem. I need to fetch posts with information from mainly three tables: users, posts and reactions (post likes).

This information has to be ordered so that the most interesting is on the top (like Facebook's own newsfeed or Instagram explore).

I wish to order this information based on other tables such as which user the current user likes the most; like which user is MOST interesting (in form of following and liking his posts) and then put it in top.

User schema:
```go
// User holds the schema definition for the User entity.
type User struct {
	ent.Schema
}

// Fields of the User.
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.Int("id"),
	}
}

// Edges of the User.
func (User) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("following", User.Type).
			From("followers"),
         }
}
```
Post schema:
```go

// Post holds the schema definition for the Post entity.
type Post struct {
	ent.Schema
}

// Fields of the Post.
func (Post) Fields() []ent.Field {
	return []ent.Field{
		field.Int("id"),
        }
}


// Edges of the Post.
func (Post) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("owner", User.Type).
			Ref("posts").
			Unique().
			Field("user_id").
			Required(),
         }
}
```
Reaction table (likes) 
```go
// Reaction holds the schema definition for the Reaction entity.
type Reaction struct {
	ent.Schema
}

// Fields of the Reaction.
func (Reaction) Fields() []ent.Field {
	return []ent.Field{
		field.Int("id"),
		field.Int("user_id"),
                // example: post id
		field.Int("reactionable_id"),
               /// example: post
		field.Int("reactionable_type"),
       }
}

// Edges of the Reaction.
func (Reaction) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("owner", User.Type).
			Ref("reactions").
			Unique().
			Field("user_id").
			Required(),
	}
}
```

**Comment by a8m** [comment] 2023-01-20 08:16
Hey @sahmadreza 👋 
Ordering by relations (or other tables) is not supported atm by the generated API. However, you can implement this using a custom `OrderFunc`. See this example from the doc: https://entgo.io/docs/paging#custom-ordering. 

Closing, as this is a duplicate of https://github.com/ent/ent/issues/2807.

**Closed by a8m** 2023-01-20 08:16 UTC
