### ISSUE TITLE
/ent/gen/runtime.init.0()

### ISSUE THREAD

**Issue by wonderfate** [ent/ent#2888] opened 2022-08-29 22:20 UTC
Here's what happened？

![image](https://user-images.githubusercontent.com/43459833/187308127-d02a45c3-ac93-4010-8ee5-5acc38958acd.png)

When I customized the cmd I got an error

![image](https://user-images.githubusercontent.com/43459833/187308474-293f10b0-7287-430a-9d2e-7813385908cd.png)

**Comment by a8m** [comment] 2022-08-30 04:45
Hey @wonderfate and thanks for reporting this issue 👋🏻

Can you elaborate on what do you mean by “customizing the cmd”? Any way I can reproduce this?

**Comment by wonderfate** [comment] 2022-08-30 08:55
Hi @a8m  

I can't reproduce that. 

I don't know when the content in this file was generated `/ent/runtime/runtime.go`

![image](https://user-images.githubusercontent.com/43459833/187394304-7d3f4b19-0435-42d9-9428-de9574fc7345.png)

**Comment by a8m** [comment] 2022-08-30 08:57
Can you please paste here the generated file? It looks like line 107 panics.

Also, can you please update to the latest master, run codegen and report if you still get this?

~~~
go get entgo.io/ent@master
~~~

**Comment by wonderfate** [comment] 2022-08-30 09:38
get this pinic  when I add or modify the field

```go
// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"apps/app/internal/ent/gen/user"
	"apps/app/internal/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	.
	.
	.
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields3[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields3[1].Descriptor()
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescPhoneIsoCode is the schema descriptor for phone_iso_code field.
	userDescPhoneIsoCode := userFields[3].Descriptor()
	// user.PhoneIsoCodeValidator is a validator for the "phone_iso_code" field. It is called by the builders before save.
	user.PhoneIsoCodeValidator = userDescPhoneIsoCode.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[4].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[5].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescNickname1 is the schema descriptor for nickname1 field.
	userDescNickname1 := userFields[6].Descriptor()
	// user.Nickname1Validator is a validator for the "nickname1" field. It is called by the builders before save.
	user.Nickname1Validator = userDescNickname1.Validators[0].(func(string) error)
	// userDescNickname is the schema descriptor for nickname field.
	userDescNickname := userFields[7].Descriptor()
	// user.NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	user.NicknameValidator = userDescNickname.Validators[0].(func(string) error)

        // ==========>>>> this line  <<<<===========
        // ==========>>>> this line  <<<<===========
        // ==========>>>> this line  <<<<===========
	// userDescAvatar is the schema descriptor for avatar field.
	userDescAvatar := userFields[8].Descriptor()
        // ==========>>>> this line  <<<<===========
        // ==========>>>> this line  <<<<===========
        // ==========>>>> this line  <<<<===========


	// user.DefaultAvatar holds the default value on creation for the avatar field.
	user.DefaultAvatar = userDescAvatar.Default.(string)
	// user.AvatarValidator is a validator for the "avatar" field. It is called by the builders before save.
	user.AvatarValidator = userDescAvatar.Validators[0].(func(string) error)
        .
        .
        .
}

const (
	Version = "v0.11.3-0.20220830071904-3b1b75b9d7a9"           // Version of ent codegen.
	Sum     = "h1:dxyBYasfOuLgAT0IuqSXNgDDJ9ra5C+Jc8a6VqVywWo=" // Sum of ent codegen.
)
```

**Comment by a8m** [comment] 2022-08-30 09:54
@wonderfate, can you please run code generation (`go generate ./ent/...`) and report if you still get this? It looks like the `avatar` field does not exist in the schema. Can you also paste here the `User` schema? Thanks 🙏

**Comment by wonderfate** [comment] 2022-08-30 10:07
@a8m  

Sorry bro, I modified my code and now I can't reproduce it.

some code snippets as below:

my customize `cmd.go`

```go
package main

import (
	"fmt"
	"os"
	"apps/app/cmd/internal/base"
	"apps/app/cmd/internal/gen"

	appconfig "internal/app/config"

	"github.com/spf13/cobra"
	"github.com/zeromicro/go-zero/core/conf"
)

func main() {
	var rootCmd = &cobra.Command{
		Short: "project",
		Long:  `You can see "-h" flag to see all subcommands`,
		PersistentPreRun: func(command *cobra.Command, args []string) {
			configFile := appconfig.GetConfigFile(base.EtcDir, base.Env)
			conf.MustLoad(*configFile, &base.Config)
		},
	}

	rootCmd.AddCommand(
		//base.CmdMigrate,
		//base.CmdSeed,
		gen.CmdGen,
	)
	//rootCmd.PersistentFlags().StringVarP(&Env, "env", "e", "", "load .env file, example: --env=testing will use .env.testing file")

	base.RegisterGlobalFlags(rootCmd)

	if err := rootCmd.Execute(); err != nil {
		fmt.Printf("Failed to run cmd with %v: %s", os.Args, err.Error())
	}
}

```

```go
package gen

import (
	"fmt"
	"tag/pkg/console"

	"entgo.io/ent/entc"
	"entgo.io/ent/entc/gen"
	"entgo.io/ent/schema/field"
	"github.com/spf13/cobra"
)

var CmdGenSchemacode = &cobra.Command{
	Use:   "schemacode",
	Short: "Generate schema codes",
	Run:   runGenSchemacode,
}

func runGenSchemacode(command *cobra.Command, args []string) {
	singularHook := func(next gen.Generator) gen.Generator {
		return gen.GenerateFunc(func(g *gen.Graph) error {
			return next.Generate(g)
		})
	}

	err := entc.Generate(dir, &gen.Config{
		Package:  "apps/app/internal/ent/gen",
		Target:   target,
		IDType:   &field.TypeInfo{Type: field.TypeUint64},
		Features: []gen.Feature{gen.FeatureVersionedMigration},
		Hooks:    []gen.Hook{singularHook},
	})

	if err != nil {
		console.Exit(fmt.Sprintf("running ent codegen: %v", err))
	}
}
```

my `gengenerate.go`
```
//go:generate  go run -x apps/app/cmd/cmd.go gen schemacode --dir=apps/app/internal/ent/schema --target=apps/app/internal/ent/gen --etc-dir=$ETCDIR
```

**Comment by wonderfate** [comment] 2022-08-30 10:10
> @wonderfate, can you please run code generation (`go generate ./ent/...`) and report if you still get this? It looks like the `avatar` field does not exist in the schema. Can you also paste here the `User` schema? Thanks 🙏

I confirm that my schema exists the avatar field, seems to be related to `runtimes`

**Comment by a8m** [comment] 2022-08-30 10:18
My guess is that `singularHook` is responsible for this failure, but it's just an assumption because it's not the code we have in the upstream. I recommend you to use the standard Ent package and not use a modified version of it (in case it's possible), because it's constantly evolving. If something is missing or you would like to extend it, let me know and I'll try to help with it. 

I think we can close this issue because it's not something I can reproduce and fix.

**Comment by wonderfate** [comment] 2022-08-30 10:28
I originally wanted to use `singularHook` to modify the format for each table name, But it didn't seem to work, so I modified it in the Schema. 

Which package should I use? if wanna modity each table name

Yeah, thanks for your answer

**Comment by a8m** [comment] 2022-08-30 10:34
You can use `ent`/`entc` as a package (see [instructions](https://entgo.io/docs/code-gen#use-entc-as-a-package) and an [example](https://github.com/ent/ent/tree/master/examples/entcpkg)) and inject a custom codegen hook there. See also: https://entgo.io/docs/code-gen#code-generation-hooks. 

Please, feel free to join our [Discord community](https://discord.gg/qZmPgTE6RX) if you need more help with it.

**Closed by a8m** 2022-08-30 10:34 UTC
