### ISSUE TITLE
Cant use Order() with Paginate() on entgql

### ISSUE THREAD

**Issue by gsoec** [ent/ent#2973] opened 2022-09-29 00:46 UTC
```go
user.QueryGroup().
  Order(ent.Asc(
    group.FieldSortOrder,
  )).
  Paginate(ctx, after, first, before, last)
```
generated SQL
```sql
SELECT COUNT(DISTINCT "group"."id") FROM "group" 
 ORDER BY "group"."sort_order" asc;
``` 

- [ x] The issue is present in the latest release.
- [x ] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

`SQL Error [42803]: ERROR: column "sort_order" must appear in the GROUP BY clause or be used in an aggregate function`

## Expected Behavior 🤔

should remove `ORDER BY "group"."sort_order" asc`  from the query.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19  |
| Ent         | 0.11.3   |
| Database    | CockroachDB   |
| Driver      | github.com/lib/pq        |

**Comment by a8m** [comment] 2022-09-29 14:42
Hey @gsoec 👋 
You should use the generated `With<T>Order` functions. See https://github.com/ent/contrib/blob/master/entgql/internal/todo/ent/gql_pagination.go#L1067 and https://github.com/ent/contrib/blob/master/entgql/internal/todo/ent/gql_pagination.go#L1209-L1250.

Please, let me know if you need more help with this.

**Comment by syssam** [comment] 2022-10-02 06:04
@a8m
I would like to query user liked tweet list order by liked date with Paginate(), follow https://entgo.io/docs/schema-edges#m2m-bidirectional
the SQL will be, however, I could not find any solution with that.
I posted this issue the past few months, please help me.
`select * from tweet left join like on tweet.id = like.tweet_id order by like.liked_at`

**Comment by a8m** [comment] 2022-10-09 12:07
Closing as this is a duplicate of https://github.com/ent/ent/issues/2807 - an issue that is on our list for this release. 

Thanks 🙏

**Closed by a8m** 2022-10-09 12:07 UTC
