### ISSUE TITLE
func CreateGraph(ctx context.Context, client *ent.Client) error {} wont compile x2 errors

### ISSUE THREAD

**Issue by wr125** [ent/ent#1958] opened 2021-09-17 15:25 UTC
SetOwner(a8m) undifined. car.Create has no field SetOwner(a8m) 
+ 
// query the inverse edge.
	for _, ca := range cars {
		owner, err := ca.QueryOwner().Only(ctx) - undifined

- [ x] The issue is present in the latest release.
- [x ] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
Error - wont compile

## Expected Behavior 🤔
to work

complie
## Steps to Reproduce 🕹
 

Steps:

1.cut and paste start.go
2.compile with car, group and user.go
3.Error
4.

## Your Environment 🌎
linux mint

copied and paste the start.go file from here. Followed the tutorial online.

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17  |
| Ent         | unknown  | no --version command? (downloaded today)
| Database    | sqlite3   |
| Driver      | _ "github.com/mattn/go-sqlite3"      |

**Comment by a8m** [comment] 2021-09-19 07:41
Hey @wr125 and thanks for reporting this. I just ran the example in [examples/start](https://github.com/ent/ent/blob/master/examples/start/start.go) and it worked without any issues (see screenshot). Can you please provide an example file/repository for me to reproduce this? Thanks 🙏 

![image](https://user-images.githubusercontent.com/7413593/133919502-68a7fcc3-ad76-4cca-b667-ea250b139f81.png)

**Comment by wr125** [comment] 2021-09-19 20:55
![ent](https://user-images.githubusercontent.com/20228047/133942721-1f9415e2-9261-4c47-8bfc-05541309249e.png)
After cut and paste the updated code from github file start.go, I can how compile the app successfully.

**Comment by wr125** [comment] 2021-09-19 21:00
On a separete note, does ent have a working example of a front end (client side) interacting with its api layer?

**Comment by wr125** [comment] 2021-09-21 17:17
The problem is with this file https://github.com/ent/ent/blob/master/examples/start/start.go

**Comment by rotemtam** [comment] 2021-09-22 05:49
@wr125 are you running this file from within the Ent repository? In your issue description, you mentioned you copy-pasted the file. Just verifying, because this is not expected to work outside the context of the repository that has all of its dependencies

**Comment by a8m** [comment] 2021-09-24 11:15
Closing as it's not an issue in ent. Please let me know if you still need help with the getting-started tutorial.

**Closed by a8m** 2021-09-24 11:15 UTC

**Comment by wr125** [comment] 2021-09-24 11:28
ok thanks. However, I have created a database through migration put its empty because I don't know the code to fill tables (seed). I hear things like hooks, relay node,mutation etc. And have been trying to learn them for a few days now and still can't find code to populate my database. The learning curve seems high when I just want to add values to fields. Can you help?

**Comment by a8m** [comment] 2021-09-24 11:38
Hey @wr125, we don't have a special feature for seeding a database atm, but you can do the same thing we do, create a `Seed` function that accepts an `ent.Client` as an argument and just create whatever you need there. For example:

```go
func Seed(ctx context.Context, client *ent.Client) error {
	if err := client.User.CreateBulk(
		client.User.Create().SetName("admin").SetRole(user.RoleAdmin),
		client.User.Create().SetName("viewer").SetRole(user.RoleViewer),
		// ...
	).Exec(ctx); err != nil {
		return err
	}
	if err := client.Project.Create().SetName("default").Exec(ctx); err != nil {
		return err
	}
	return nil
}
```

**Comment by wr125** [comment] 2021-09-24 11:59
What would this seed look like if I have the following Product, Invoice, Categories etc. This seed func would also go in my server.go file right?

**Comment by wr125** [comment] 2021-09-24 16:01
I don't know where SetName("admin").SetRole(user.RoleAdmin) comes from! Is this a builtin value of ent (admin roles etc) or is this an example of how my entity field should look like?. Also SetName = "Name" is this the table value in db and what is "default" value here?

**Comment by a8m** [comment] 2021-09-24 20:37
This is just an example based on my personal schemas. This subject is covered in the [getting-started](https://entgo.io/docs/getting-started) tutorial on our website. Please, go over it (step by step) and let us know if you need assistance there.

**Comment by a8m** [comment] 2021-09-24 20:38
This is just an example based on my personal schemas. This subject is covered in the [getting-started](https://entgo.io/docs/getting-started) tutorial on our website. Please, go over it (step by step) and let us know if something is not clear there.
