### ISSUE TITLE
Pagination first, after with order by

### ISSUE THREAD

**Issue by tutranngoc** [ent/ent#2562] opened 2022-05-25 08:55 UTC
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
- I'm using the syntax as per your instructions here: https://entgo.io/docs/tutorial-todo-gql-paginate/
- however, I find it misbehaving with First, After and OrderBy
- this is my data after i get all and sorted by field "test"  ( field "test" has 2 values of 0 and 1 )

            orderBy:{ field: test, direction: DESC}
            
            query debug: 
            SELECT DISTINCT "todos"."id",
                "todos"."name",
                "todos"."test"
            FROM "todos" ORDER BY "todos"."test" DESC, "todos"."id" DESC
     > result:
             ![image](https://user-images.githubusercontent.com/93513209/170209166-10668f20-3b7d-4c1d-9cc0-9e60e93218cb.png)

- after, I tested order with first and after (limit: 2, total page: 3)
    1. first time with query - page 1:
        ```
               first:2, after: null, orderBy:{ field: test, direction: DESC }
         ```
         > The result is correct 
              ![image](https://user-images.githubusercontent.com/93513209/170220748-e5ee5b28-27a1-4d07-bf56-1800406c56cf.png)
    2. 2nd, page 2:
         ```
               first:2, after: "gqFpzwAAAAAAAAABoXYB", orderBy:{ field: test, direction: DESC }
               
               "gqFpzwAAAAAAAAABoXYB" (corresponding to id = 1)
               
               query debug: 
               SELECT DISTINCT  "todos"."id",
                                "todos"."name",
                                "todos"."test"
               FROM "todos"
               WHERE ("todos"."test", "todos"."id") < ($1, $2)
               ORDER BY "todos"."test" DESC, "todos"."id" DESC
               LIMIT 3 args=[1 1]
               
         ```
         > The result is correct 
              ![image](https://user-images.githubusercontent.com/93513209/170216511-5c829181-8cf5-4827-b408-0928027cf2eb.png)

    3. Final, i query to page 3 with "after" = "gaFpzwAAAAAAAAAE"   corresponding to id = 4 
        ```
            first:2, after: "gaFpzwAAAAAAAAAE", orderBy:{ field: test, direction: DESC }
           
            query debug: 
               SELECT DISTINCT "todos"."id",
                "todos"."name",
                "todos"."test"
              FROM "todos"
              WHERE  "todos"."id" < $1
              ORDER BY "todos"."test" DESC, "todos"."id" DESC
              LIMIT 3 args=[4]
            
        ```
        > wrong result
             ![image](https://user-images.githubusercontent.com/93513209/170218559-20cafe11-dbcd-4401-a504-8b5c618d0eca.png)
            According to the second return, I see it didn't go on to next element is 
             `  
                "node": {
                   "id": "3",
                   "name": "c",
                   "test": 0
                 }
             `
             but back to the first page
        
        > expected results
        `
            "edges": [
                {
                  "node": {
                    "id": "3",
                    "name": "c",
                    "test": 0
                  },
                  "cursor": "gaFpzwAAAAAAAAAD"
                }
          ]
        `  

My code
```
       query := client.Debug().Todo.Query()
	var opts []ent.TodoPaginateOption
	if params.Where != nil {
		opts = append(opts, ent.WithTodoFilter(params.Where.Filter))
	}
	if params.OrderBy != nil {
		opts = append(opts, ent.WithTodoOrder(params.OrderBy))
	}
	return query.Paginate(ctx, params.After, params.First, params.Before, params.Last, opts...)
```
Maybe I'm wrong somewhere, can you help me. Thank all !!

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17.2  |
| Ent         | 0.10.0   |
| Database    | Postgress   |

**Comment by springnguyen** [comment] 2022-05-25 09:13
yeah , this bug make me headache :'I

**Comment by trichruiphe** [comment] 2022-05-25 09:15
so, I have same problem, I'm spend a bunch of hour to search it on google but cant find anything relate with this problem

**Comment by a8m** [comment] 2022-05-29 05:45
Closing because I was not able to reproduce this.

Please, update to ent/contrib@master and reopen if you still face an issue.

**Closed by a8m** 2022-05-29 05:45 UTC
