### ISSUE TITLE
Test failures on 32-bit archs

### ISSUE THREAD

**Issue by CyrilBrulebois** [ent/ent#3126] opened 2022-11-27 14:02 UTC
- [x] The issue is present in the latest release: 0.11.4
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Once the patch mentioned in #3125 is applied, I'm getting a bunch of failures anyway. Values like `1<<32` and `2<32` (under this form or as 4294967296 and 8589934592) are used in various places, and if the goal was to test edge cases, it seems to be working quite fine…

Test `TestMigrate_Diff` reports a missing line in the “actual” output:

```
-INSERT INTO sqlite_sequence (name, seq) VALUES ("users", 4294967296);
```

Test `TestMySQL_Create` fails in all “universal id”-related subtests:

```
=== RUN   TestMySQL_Create/universal_id_for_all_tables
    mysql_test.go:1368:
                Error Trace:    /path/to/golang-entgo-ent/_build/src/entgo.io/ent/dialect/sql/schema/mysql_test.go:1368
                Error:          Not equal:
                                expected: false
                                actual  : true
                Test:           TestMySQL_Create/universal_id_for_all_tables
                Messages:       sql/schema: ExecQuery: could not match actual sql: "ALTER TABLE `groups` AUTO_INCREMENT = 0" with expected regexp "ALTER TABLE `groups` AUTO_INCREMENT = 4294967296$": call to Rollback transaction, was not expected, next expectation is: ExpectedExec => expecting Exec or ExecContext which:
                                  - matches sql: 'ALTER TABLE `groups` AUTO_INCREMENT = 4294967296$'
                                  - is without arguments
                                  - should return Result having:
                                      LastInsertId: 0
                                      RowsAffected: 1
=== RUN   TestMySQL_Create/universal_id_for_new_tables
    mysql_test.go:1368:
                Error Trace:   /path/to/golang-entgo-ent/_build/src/entgo.io/ent/dialect/sql/schema/mysql_test.go:1368
                Error:          Not equal:
                                expected: false
                                actual  : true
                Test:           TestMySQL_Create/universal_id_for_new_tables
                Messages:       sql/schema: ExecQuery: could not match actual sql: "ALTER TABLE `groups` AUTO_INCREMENT = 0" with expected regexp "ALTER TABLE `groups` AUTO_INCREMENT = 4294967296$": call to Rollback transaction, was not expected, next expectation is: ExpectedExec => expecting Exec or ExecContext which:
                                  - matches sql: 'ALTER TABLE `groups` AUTO_INCREMENT = 4294967296$'
                                  - is without arguments
                                  - should return Result having:
                                      LastInsertId: 0
                                      RowsAffected: 1
=== RUN   TestMySQL_Create/universal_id_for_restored_tables
    mysql_test.go:1368:
                Error Trace:    /path/to/golang-entgo-ent/_build/src/entgo.io/ent/dialect/sql/schema/mysql_test.go:1368
                Error:          Not equal:
                                expected: false
                                actual  : true
                Test:           TestMySQL_Create/universal_id_for_restored_tables
                Messages:       sql/schema: ExecQuery: could not match actual sql: "ALTER TABLE `groups` AUTO_INCREMENT = 0" with expected regexp "ALTER TABLE `groups` AUTO_INCREMENT = 4294967296$": call to Rollback transaction, was not expected, next expectation is: ExpectedExec => expecting Exec or ExecContext which:
                                  - matches sql: 'ALTER TABLE `groups` AUTO_INCREMENT = 4294967296$'
                                  - is without arguments
                                  - should return Result having:
                                      LastInsertId: 0
                                      RowsAffected: 1
=== RUN   TestMySQL_Create/universal_id_mismatch_with_ent_types
    mysql_test.go:1368:
                Error Trace:    /path/to/golang-entgo-ent/_build/src/entgo.io/ent/dialect/sql/schema/mysql_test.go:1368
                Error:          Not equal:
                                expected: false
                                actual  : true
                Test:           TestMySQL_Create/universal_id_mismatch_with_ent_types
                Messages:       call to Commit transaction, was not expected, next expectation is: ExpectedQuery => expecting Query, QueryContext or QueryRow which:
                                  - matches sql: 'SELECT `AUTO_INCREMENT` FROM `INFORMATION_SCHEMA`\.`TABLES` WHERE `TABLE_SCHEMA` = \(SELECT DATABASE\(\)\) AND `TABLE_NAME` = \?$'
                                  - is with arguments:
                                    0 - users
                                  - should return rows:
                                    row 0 - [1]
```

Test `TestPostgres_Create` also fails in all “universal ids”-related subtests:

```
=== RUN   TestPostgres_Create/universal_id_for_all_tables
    postgres_test.go:1003:
                Error Trace:    /path/to/golang-entgo-ent/_build/src/entgo.io/ent/dialect/sql/schema/postgres_test.go:1003
                Error:          Not equal:
                                expected: false
                                actual  : true
                Test:           TestPostgres_Create/universal_id_for_all_tables
                Messages:       sql/schema: ExecQuery: could not match actual sql: "ALTER TABLE "groups" ALTER COLUMN "id" RESTART WITH 1" with expected regexp "ALTER TABLE "groups" ALTER COLUMN "id" RESTART WITH 4294967296": call to Rollback transaction, was not expected, next expectation is: ExpectedExec => expecting Exec or ExecContext which:
                                  - matches sql: 'ALTER TABLE "groups" ALTER COLUMN "id" RESTART WITH 4294967296'
                                  - is without arguments
                                  - should return Result having:
                                      LastInsertId: 0
                                      RowsAffected: 1
=== RUN   TestPostgres_Create/universal_id_for_new_tables
    postgres_test.go:1003:
                Error Trace:    /path/to/golang-entgo-ent/_build/src/entgo.io/ent/dialect/sql/schema/postgres_test.go:1003
                Error:          Not equal:
                                expected: false
                                actual  : true
                Test:           TestPostgres_Create/universal_id_for_new_tables
                Messages:       sql/schema: ExecQuery: could not match actual sql: "ALTER TABLE "groups" ALTER COLUMN "id" RESTART WITH 1" with expected regexp "ALTER TABLE "groups" ALTER COLUMN "id" RESTART WITH 4294967296": call to Rollback transaction, was not expected, next expectation is: ExpectedExec => expecting Exec or ExecContext which:
                                  - matches sql: 'ALTER TABLE "groups" ALTER COLUMN "id" RESTART WITH 4294967296'
                                  - is without arguments
                                  - should return Result having:
                                      LastInsertId: 0
                                      RowsAffected: 1
=== RUN   TestPostgres_Create/universal_id_for_restored_tables
    postgres_test.go:1003:
                Error Trace:    /path/to/golang-entgo-ent/_build/src/entgo.io/ent/dialect/sql/schema/postgres_test.go:1003
                Error:          Not equal:
                                expected: false
                                actual  : true
                Test:           TestPostgres_Create/universal_id_for_restored_tables
                Messages:       sql/schema: ExecQuery: could not match actual sql: "ALTER TABLE "groups" ALTER COLUMN "id" RESTART WITH 1" with expected regexp "ALTER TABLE "groups" ALTER COLUMN "id" RESTART WITH 4294967296": call to Rollback transaction, was not expected, next expectation is: ExpectedExec => expecting Exec or ExecContext which:
                                  - matches sql: 'ALTER TABLE "groups" ALTER COLUMN "id" RESTART WITH 4294967296'
                                  - is without arguments
                                  - should return Result having:
                                      LastInsertId: 0
                                      RowsAffected: 1
```

Test `TestSQLite_Create` also fails in all “universal ids”-related subtests:

```
=== RUN   TestSQLite_Create/universal_id_for_all_tables
    sqlite_test.go:443:
                Error Trace:    /path/to/golang-entgo-ent/_build/src/entgo.io/ent/dialect/sql/schema/sqlite_test.go:443
                Error:          Not equal:
                                expected: false
                                actual  : true
                Test:           TestSQLite_Create/universal_id_for_all_tables
                Messages:       sql/schema: ExecQuery 'INSERT INTO `sqlite_sequence` (`name`, `seq`) VALUES (?, ?)', arguments do not match: argument 1 expected [int64 - 4294967296] does not match actual [int64 - 0]: sql/sqlite: set 'foreign_keys = on': ExecQuery: could not match actual sql: "PRAGMA foreign_keys = on" with expected regexp "INSERT INTO `sqlite_sequence` \(`name`, `seq`\) VALUES \(\?, \?\)$": call to Rollback transaction, was not expected, next expectation is: ExpectedExec => expecting Exec or ExecContext which:
                                  - matches sql: 'INSERT INTO `sqlite_sequence` \(`name`, `seq`\) VALUES \(\?, \?\)$'
                                  - is with arguments:
                                    0 - groups
                                    1 - 4294967296
                                  - should return Result having:
                                      LastInsertId: 0
                                      RowsAffected: 1
=== RUN   TestSQLite_Create/universal_id_for_restored_tables
    sqlite_test.go:443:
                Error Trace:    /path/to/golang-entgo-ent/_build/src/entgo.io/ent/dialect/sql/schema/sqlite_test.go:443
                Error:          Not equal:
                                expected: false
                                actual  : true
                Test:           TestSQLite_Create/universal_id_for_restored_tables
                Messages:       sql/schema: ExecQuery 'INSERT INTO `sqlite_sequence` (`name`, `seq`) VALUES (?, ?)', arguments do not match: argument 1 expected [int64 - 4294967296] does not match actual [int64 - 0]: sql/sqlite: set 'foreign_keys = on': ExecQuery: could not match actual sql: "PRAGMA foreign_keys = on" with expected regexp "INSERT INTO `sqlite_sequence` \(`name`, `seq`\) VALUES \(\?, \?\)$": call to Rollback transaction, was not expected, next expectation is: ExpectedExec => expecting Exec or ExecContext which:
                                  - matches sql: 'INSERT INTO `sqlite_sequence` \(`name`, `seq`\) VALUES \(\?, \?\)$'
                                  - is with arguments:
                                    0 - groups
                                    1 - 4294967296
                                  - should return Result having:
                                      LastInsertId: 0
                                      RowsAffected: 1
```

## Expected Behavior 🤔

The test suite shouldn't fail.

## Steps to Reproduce 🕹

Same as in #3125, with the extra patch applied.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19.3 |
| Ent         | 0.11.4 |

**Comment by a8m** [comment] 2022-11-27 14:08
Thanks for reporting this.

Closing as it's a duplicate of #3125 🙏

**Closed by a8m** 2022-11-27 14:08 UTC
