### ISSUE TITLE
Multi Primary key

### ISSUE THREAD

**Issue by alv00** [ent/ent#3542] opened 2023-05-16 02:00 UTC
hi~

1、Can I create multiple primary keys for a table now? 
For example, I want the schema of this table to be like this：
```
CREATE TABLE `__all_sys_parameter` (
    `zone` varchar(128) NOT NULL,
    `svr_type` varchar(16) NOT NULL,
    `svr_ip` varchar(46) NOT NULL,
    .......
    PRIMARY KEY (param_name`, `zone`, `svr_type`, `svr_ip`, `svr_port`, `name`)
```

2、Because I don't want to have an auto-incrementing id column, so I define the id column like this
```
field.String("id").StorageKey("param_name").SchemaType(map[string]string{
    dialect.MySQL: "varchar(128)", // Override MySQL.
    }),
```
Now this table has only one primary key
```
PRIMARY KEY (`param_name`)
```

**Comment by a8m** [comment] 2023-05-16 07:49
Hey, @alv00 👋 
As explained in our Discord, Ent currently does not support composite primary keys (besides join tables).

Closing, as this is a duplicate of #400. Thanks 🙏

**Closed by a8m** 2023-05-16 07:49 UTC
