### ISSUE TITLE
entproto do not compatible with JSON field

### ISSUE THREAD

**Issue by wahello** [ent/ent#2929] opened 2022-09-15 03:53 UTC
- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

as struct like Such as:
```

import (
	"entgo.io/contrib/entproto"
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"

)
type Node struct {
	ent.Schema
}

func (Node) Mixin() []ent.Mixin {
	return []ent.Mixin{
	}
}

func (Node) Fields() []ent.Field {

	return []ent.Field{

		field.String("hostname").MaxLen(512).MinLen(3).Annotations(
			entproto.Field(100),
		),

		field.String("ip").MaxLen(64).Annotations(
			entproto.Field(101),
		),  

		field.Float("priority").Default(99999).Annotations(
			entproto.Field(104),
		),
   
		field.JSON("tag", []string{}).Default([]string{}).Annotations(
			entproto.Field(150),
		),

	}
}

func (Node) Edges() []ent.Edge {
	return []ent.Edge{ 
	}
}

func (Node) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("hostname"),
		index.Fields("ip"), 
	}
}

func (Node) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entproto.Message(entproto.PackageName("entpb")),
		entproto.Service(),
	}
}

```

And  generate the model the following code 
```
package main

import (
	"log"

	"entgo.io/contrib/entproto"
	"entgo.io/ent/entc"
	"entgo.io/ent/entc/gen"
)

func main() {

	err := entc.Generate("./internal/schema/entity", &gen.Config{
		Features: []gen.Feature{
			// gen.FeatureEntQL,
			// gen.FeatureSnapshot,
			gen.FeatureSchemaConfig,
			gen.FeatureLock,
			gen.FeatureModifier,
			gen.FeatureUpsert,
		},
		Hooks: []gen.Hook{
			entproto.Hook(),
		},
		Package: "inpman/internal/gen/ent",
		Target:  "./internal/gen/ent",
		Templates: []*gen.Template{
			gen.MustParse(gen.NewTemplate("mutation_input").ParseDir("./internal/schema/template")),
		},
	})

	if err != nil {
		log.Fatalf("running ent codegen: %v", err)
	}
}

```
Error printed with tip like:
```
running ent codegen: entproto: failed parsing ent graph: file "entpb/entpb.proto" included an unresolvable reference to "Node"
```
If remove the line 
```
		field.JSON("tag", []string{}).Default([]string{}).Annotations(
			entproto.Field(150),
		),
```
the above code works.

## What's the problem?

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.18  |
| Ent         | 0.11.2   |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by rotemtam** [comment] 2022-09-15 06:34
Hi @wahello 

Thanks for reaching out. Correct, `field.JSON` isn't supported with `entproto`. There's an open discussion on how the proto/gRPC layer should behave in this case:
https://github.com/ent/ent/discussions/1690

Would you mind responding there with how you would expect this feature to behave? 

Closing as the issue is captured in #1690

**Closed by rotemtam** 2022-09-15 06:34 UTC
