### ISSUE TITLE
`constraint failed: one of [x] is already connected to a different y` but it's the same ID

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2697] opened 2022-06-28 01:00 UTC
## Current Behavior 😯

I'm encountering this strange issue:

```
query=UPDATE "players" SET "team_player" = $1 WHERE "id" = $2 AND "team_player" IS NULL args=[6 11]

error="ent: constraint failed: one of [11] is already connected to a different team_player"
```

the "different team_player" is the same, but it doesn't understand it.

I think this is a bug.

## Expected Behavior 🤔

It recognizes is the same ID.

## Steps to Reproduce 🕹

I don't have time right now. :sad:

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.18.3  |
| Ent         | entgo.io/contrib v0.2.1-0.20220623093601-df0921394080, entgo.io/ent v0.10.2-0.20220622152053-3bb5292c83bf   |
| Database    | PG   |
| Driver      | pgx        |

**Comment by a8m** [comment] 2022-06-28 21:40
Hey @frederikhors and thanks for opening this issue.

This is the expected behavior and not a bug. Unlike `Set`, you can't `Add` an edge multiple times, even if it's connected to the same node. We treat it as a duplicate edge and therefore calling `Add` with the same values fails as duplicate edges are not allowed (they may contain metadata with different values). This behavior is the same for all non-unique edge types (O2M, M2M). 

In case users want to override all edges in each `Update`, they can call: `ClearE().AddE(...)`.

---

Worth mentioning a few words about the implementation of the example above:

When adding a one-2-many edge, the generated statement looks as follows:

```sql
UPDATE child_table SET parent_id=parent_id WHERE id IN (child_ids...) AND parent_id IS NULL
```

This way, we ensure destination nodes are not connected to other nodes under the same edge type. The only way to check if the operations succeed is to compare `affected_rows == child_ids`. In case it's not, we know that one of the destination nodes is already connected with this edge and we fail (we don't know which one). This way, we can ensure the behavior expected above without loading the records or executing additional queries to the database.

Closing as there's no action item here and this behavior is not going to change. Thanks and I hope it helps.

**Closed by a8m** 2022-06-28 21:40 UTC
