### ISSUE TITLE
entc/gen: mutation do not ignore zero value of GoType which implement database/sql/driver.Valuer

### ISSUE THREAD

**Issue by dodangquan** [ent/ent#3326] opened 2023-02-18 20:36 UTC
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

I've created a custom `GoType` which implemented `database/sql/driver.Valuer`. The new custom `GoType` is used in `ent/schema` with `DefaultFunc`. If i set field is zero value of custom `GoType` then the zero value is also saved to database instead of a default value.

```go
type User struct {
	ent.Schema
}

// Fields of the User.
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.Int("age"),
		field.String("name"),
		field.String("gender").
			Optional().
			GoType(sql.NullString{}).
			DefaultFunc(func() sql.NullString {
				return sql.NullString{
					String: "Unknown",
					Valid:  true,
				}
			}),
	}
}
```

`mutation.go`

```go
// ...
func (m *UserMutation) Gender() (r sql.NullString, exists bool) {
	v := m.gender
	if v == nil {
		return
	}
	return *v, true
}
// ...
```

`user_create.go`
```go
...
func (uc *UserCreate) defaults() {
	if _, ok := uc.mutation.Gender(); !ok {
		v := user.DefaultGender()
		uc.mutation.SetGender(v)
	}
}

// ...

func (uc *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
// ...
	if value, ok := uc.mutation.Gender(); ok {
		_spec.SetField(user.FieldGender, field.TypeString, value)
		_node.Gender = value
	}
// ...
}
```

```go
client.User.Create().SetAge(20).SetName("test").SetGender(sql.NullString{}).Save(ctx)
```

## Expected Behavior 🤔

Declared default value in ent/schema should be saved to database instead of zero value

## Steps to Reproduce 🕹

Steps:

1. Create a new custom `GoType` which implements `database/sql/driver.Valuer`
2. Use new `GoType` with `DefaultFunc` in schema
3. Set mutation's field is zero value of custom `GoType` on create a new record
4. Exec mutation query

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19.5  |
| Ent         | v0.11.9-0.20230213144729-fc28e223f837   |
| Database    | Postgres   |
| Driver      | github.com/jackc/pgx/v5 v5.2.0        |

**Comment by a8m** [comment] 2023-02-20 11:29
Hey @dodangquan 👋 

> If i set field is zero value of custom GoType then the zero value is also saved to database instead of a default value.

This is actually the expected behavior. Ent cannot distinguish when the zero value is expected (which should stay this way, IMO) because `false` is the zero value of boolean types, 0 for integers, etc.

The solution is to accept pointers in your API (e.g., HTTP body or GraphQL mutation) and use the `SetNillable<F>` methods for setting the field value only if the input is not `nil`. e.g., `SetNillableGenerate(v)`. Another alternative is to add this custom logic using [schema hooks](https://entgo.io/docs/hooks#schema-hooks) as follows:

```go
hook.On(
	func(next ent.Mutator) ent.Mutator {
		return hook.UserFunc(func(ctx context.Context, m *gen.UserMutation) (ent.Value, error) {
			if g, ok := m.Gender(); ok g == zeroGender {
				m.SetGender(defaultGender)
			}
			return next.Mutate(ctx, m)
		})
	},
	// Limit the hook only for create operations.
	ent.OpCreate,
),
```

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎

**Closed by a8m** 2023-02-20 11:29 UTC
