### ISSUE TITLE
sql: Querying from a committed transaction record causes error

### ISSUE THREAD

**Issue by tankbusta** [ent/ent#2102] opened 2021-11-02 21:40 UTC
While operating on a created entity of a successful transaction, using `QueryXXX` APIs that may be present for edges will fail with `sql: transaction has already been comitted or rolled back`

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Instead of a successful edge query, `sql: transaction has already been comitted or rolled back` is returned.

## Expected Behavior 🤔

On a successful transaction commit, any newly created records that were created under the transaction should have `config.driver` point to a non-transactable version of the driver (if I understand what's going on behind the scenes).

## Steps to Reproduce 🕹

Visit [Bug Repo](https://github.com/tankbusta/ent-txn-commit-bug)

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17.1  |
| Ent         | `87e21993097e`   |
| Database    | Postgres |
| Driver      | https://github.com/lib/pq       |

**Comment by rotemtam** [comment] 2021-11-03 05:51
Hey @tankbusta 

Thanks for reaching out! Ca you please submit a repo with a test reproducing your issue? We have a shiny new [bug template repo](https://github.com/ent/bug) just for that. 
Thanks 🙏🙏🙏

**Comment by a8m** [comment] 2021-11-03 09:07
Hey @tankbusta 👋, and thanks for taking the time to create a bug repository. 

Each generated entity has a method named `Unwrap` that unwraps the entity from the transaction after it was closed so that all future queries will be executed through the driver which created the transaction. That means, the following change will fix your issue:

```diff
+	createdProduct = createdProduct.Unwrap()
	users, err := createdProduct.QueryCreatedBy().All(ctx)
```

**Comment by a8m** [comment] 2021-11-03 09:42
A PR for updating the [Transactions docs](https://entgo.io/docs/transactions) is more than welcome 🙏 😃

**Comment by tankbusta** [comment] 2021-11-03 12:07
Ah, dang how did I miss Unwrap! I was looking for a method to potentially reset things.

I'd be more than happy to submit a PR to include Unwrap in the documentation. Although I'm curious why this wouldn't be the automatic behavior. Is there something I'm not thinking of that would make it undesirable behavior? 

Thanks!

**Comment by a8m** [comment] 2021-11-03 12:29
> Although I'm curious why this wouldn't be the automatic behavior. Is there something I'm not thinking of that would make it undesirable behavior?

I assumed this question will come up 😃. Before we added this, we found out that when users use "transactional entities"  outside the transaction (e.g. after GraphQL mutation was finished), it's either because they do something wrong or it's intentional and the use case is valid. However, both cases are not so common, and I didn't want to add "magic support" for something that can prevent bugs or lead to undesired behavior. For example, the transaction was set to isolation level `sql.LevelSerializable`, and 2 identical queries can return different records.

```go
u.QueryPets().All(ctx)

// ....

// Magically unwrap returns different records.  
u.QueryPets().All(ctx)
```

**Comment by tankbusta** [comment] 2021-11-03 12:52
> I assumed this question will come up 😃

You can count on that from me! ;) 

Thanks for that explanation, that all tracks!

**Comment by giautm** [comment] 2021-11-03 14:07
I found this issue right before I reviewed the code of the same case.

**Comment by a8m** [comment] 2021-11-04 08:21
> I'd be more than happy to submit a PR to include Unwrap in the documentation.

@tankbusta, let me know if you plan to open a PR as I want to close the issue. Thanks 🙏

**Comment by tankbusta** [comment] 2021-11-04 13:37
I do, I'll try to have it up at some point today.

You're free to close it and I'll just reference it :)

**Closed** 2021-11-05 08:09 UTC
