### ISSUE TITLE
Can set extra fields in M2M relationship table?

### ISSUE THREAD

**Issue by Xwudao** [ent/ent#1401] opened 2021-03-29 04:01 UTC
Suppose I have two tables, student table and class table (M2M)
`Ent ` generates their association table, but this table has only two fields (their primary key)
How can I add other fields to this relationship table? For example, I want to add a time point of their relationship establishment field

**Comment by 201RichK** [comment] 2021-03-29 11:58
https://github.com/ent/ent/issues/56

**Comment by a8m** [comment] 2021-03-30 08:18
Hey @Xwudao and thanks for opening this issue. 
As mentioned in https://github.com/ent/ent/issues/1400#issuecomment-808929056, this is not supported by the framework atm, but we're going to add support for this soon.

Closing because it's a duplicate of #1061. Please follow this issue to get updates on this feature. Thanks 🙏

**Closed by a8m** 2021-03-30 08:18 UTC

**Comment by Xwudao** [comment] 2021-03-30 08:22
Thanks for your reply.
