### ISSUE TITLE
Not nullable time field with MySQL 5.7

### ISSUE THREAD

**Issue by iwata** [ent/ent#1893] opened 2021-08-31 11:23 UTC
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

I created a repository for this issue.
https://github.com/iwata/ent-issue

I think this issue is related with https://github.com/ent/ent/issues/1541.

## Current Behavior 😯

```sh
go run cmd/main.go
2021/08/31 20:08:49 failed to get a user: sql: Scan error on column index 2, name "created_at": unsupported Scan, storing driver.Value type []uint8 into type *time.Time
exit status 1
```

And it creates `users` table, but not expected about `created_at`.
```sh
mysql -h 127.0.0.1 -P 3306 -u root -ppass test -e 'desc users'
+------------+--------------+------+-----+---------+----------------+
| Field      | Type         | Null | Key | Default | Extra          |
+------------+--------------+------+-----+---------+----------------+
| id         | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| name       | varchar(255) | NO   |     | unknown |                |
| created_at | timestamp    | YES  |     | NULL    |                |
+------------+--------------+------+-----+---------+----------------+
```

## Expected Behavior 🤔

```sh
go run cmd/main.go
select a user successfully

```

And it should create `users` looks like below.
```sh
mysql -h 127.0.0.1 -P 3306 -u root -ppass test -e 'desc users'
+------------+--------------+------+-----+---------+----------------+
| Field      | Type         | Null | Key | Default | Extra          |
+------------+--------------+------+-----+---------+----------------+
| id         | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| name       | varchar(255) | NO   |     | unknown |                |
| created_at | timestamp    | NO   |     | NULL    |                |
+------------+--------------+------+-----+---------+----------------+
```
`created_at` shouldn't be nullable.

## Steps to Reproduce 🕹

Steps:

1. `git clone git@github.com:iwata/ent-issue.git`
2. `cd ent-issue`
3. `docker compose up -d`
4. `go mod download`
5. `go run cmd/main.go`

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17  |
| Ent         | 0.9.1   |
| Database    | Mysql 5.7  |
| Driver      | https://github.com/go-sql-driver/mysql 1.6.0|

**Comment by a8m** [comment] 2021-09-01 09:33
Thanks, @iwata for opening this issue. Regarding your question, the reason is mentioned in the MySQL migration code:
https://github.com/ent/ent/blob/79716e47d0c892240e2bd5383d688213795d349a/dialect/sql/schema/mysql.go#L262-L264

Any suggestion for other expected behavior?

**Comment by iwata** [comment] 2021-09-01 09:39
@a8m 
Okay, how can I avoid the following?
`2021/08/31 20:08:49 failed to get a user: sql: Scan error on column index 2, name "created_at": unsupported Scan, storing driver.Value type []uint8 into type *time.Time
exit status 1`

**Comment by a8m** [comment] 2021-09-01 10:59
@iwata, can you please paste here the relevant ent/schema for this issue and the code you use to query? Thanks 🙏

**Comment by iwata** [comment] 2021-09-01 11:01
@a8m 

Here it is from https://github.com/iwata/ent-issue/blob/master/ent/schema/user.go#L16-L21.

```go
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").Default("unknown"),
		field.Time("created_at").Immutable().Default(time.Now),
	}
}
```

**Comment by a8m** [comment] 2021-09-02 06:01
Hey @iwata, I found the issue. You should add the [`parseTime=true`](https://github.com/go-sql-driver/mysql#loc)  parameter to the connection string.

![image](https://user-images.githubusercontent.com/7413593/131789879-abca5b39-ff42-487d-952d-0faa70f1bed7.png)

![image](https://user-images.githubusercontent.com/7413593/131789965-a6377cad-f723-4a5d-8ba0-f106e764f396.png)


----

I must say that this is the first time I have tried GitHub workspace (to debug your issue) and I'm in shock. It took me less than a minute to solve this issue. Definitely going to start using it for bug reporting and will write about it a blog post.

Closing and thanks 🙏

**Closed by a8m** 2021-09-02 06:01 UTC
Labels: Question

**Comment by iwata** [comment] 2021-09-02 06:04
@a8m 
That makes sense!
Thanks for your kindness!
