### ISSUE TITLE
schema import

### ISSUE THREAD

**Issue by phpmaple** [ent/ent#1716] opened 2021-07-14 03:09 UTC
ent support generate schema from sql file, or dbml file, and ent should export schema sql, or graph image

**Comment by a8m** [comment] 2021-07-16 11:22
Hey @phpmaple and thanks for raising up these features.

@zeevmoney is working on adding support for generating ent/schema from SQL schema (this is a duplicate of https://github.com/ent/ent/issues/967). 

You can use the [offline migration mode](https://entgo.io/docs/migrate#offline-mode) if you want to export an SQL schema to a file/stdout. 

Regarding exporting an ER or a graph diagram - please see [a8m/enter](https://github.com/a8m/enter) for now. If someone wants to work on generating a graph diagram, I'll be more than happy to support them (they can ping me on our [Slack channel](https://entgo.io/docs/slack/)). 

Closing and thanks 🙏

**Closed by a8m** 2021-07-16 11:22 UTC
