### ISSUE TITLE
CockroachDB insert fails: sql/schema: ERROR: unknown function: to_regclass() (SQLSTATE 42883)

### ISSUE THREAD

**Issue by Southclaws** [ent/ent#2545] opened 2022-05-16 12:25 UTC
I wanted to try getting my app running with CockroachDB's cloud for easy demos but it seems incompatible as maybe CRDB doesn't support this `to_regclass` function which is documented as "get the OID of the named relation".

Is there anything I can do to polyfill/remove this call so it's compatible? Or is CRDB not supported completely?

Thanks!

The failing test is here: https://github.com/Southclaws/storyden/blob/main/api/src/resources/post/db_test.go#L23 point [this](https://github.com/Southclaws/storyden/blob/main/api/src/infra/db/test.go#L22) to a CRDB instance (docker run should work out of the box, or paste a cockroach cloud instance URL here) and run this test to see reproduce the issue.

**Comment by hedwigz** [comment] 2022-05-17 07:46
Hey @Southclaws :wave: thanks for reporting this  
I am working on the integration of CockroachDB with Atlas (the migration engine of Ent).  
For reference, there's an issue on Atlas [here](https://github.com/ariga/atlas/issues/785) and for `to_regclass` support on CockroachDB [here](https://github.com/cockroachdb/cockroach/issues/20296#issuecomment-1066140651)  
I'd be happy to see you on [Discord](https://discord.gg/zZ6sWVg6NT) where I'll share updates on the progress and internal dev insights :rocket:

**Comment by a8m** [comment] 2022-05-17 07:52
Hey @Southclaws and @hedwigz 👋 

I created a channel for this in our Discord. Please, feel free to join - https://discord.gg/KvxFZGY2mu

Closing as it's a duplicate of https://github.com/ariga/atlas/issues/785. Thanks 🙏

**Closed by a8m** 2022-05-17 07:52 UTC

**Comment by Southclaws** [comment] 2022-05-17 09:41
Thanks! I forgot about Atlas, that explains why I couldn't find anything similar in this repo by searching, thanks! Looking forward to seeing support, I can offer help testing if needed!
