### ISSUE TITLE
Edge Schema Table for polymorphic m2m relation. 

### ISSUE THREAD

**Issue by kbumsik** [ent/ent#3110] opened 2022-11-22 04:50 UTC
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.
  - [x] There is similar issue #1048 but this issue is for more specific use cases.

## Summary 💡

Polymorphic m2m relation table.

## Motivation 🔦

Let's say "Labels" in Github used in Issues,PRs,Discussions, and etc. Instead of making m2m join table (or edge schema table in Ent terms) for each types, it would be great if we keep only one polymorphic m2m relation table.

SQL-level implementation for "Labels" is well described in the GitLab Database Guides: https://docs.gitlab.com/ee/development/database/filtering_by_label.html

```sql
SELECT
    issues.*
FROM
    issues
    INNER JOIN label_links ON label_links.target_id = issues.id
        AND label_links.target_type = 'Issue'
    INNER JOIN labels ON labels.id = label_links.label_id
WHERE
    issues.project_id = 13083
    AND (issues.state IN ('opened'))
    AND labels.title IN ('Plan', 'backend')
GROUP BY
    issues.id
HAVING (COUNT(DISTINCT labels.title) = 2)
ORDER BY
    issues.updated_at DESC,
    issues.id DESC
LIMIT 20 OFFSET 0
```

As mentioned in the GitLab link, this is not the ideal query, but you will get how the relation look like.

**Comment by a8m** [comment] 2022-11-27 14:50
Hey, @kbumsik, and it's great to see you here again 👋 

This is a feature we want to support, but we have 2 blockers at the moment: we want to use Go generics for this, which still have some regressions, and that's why it was not added to the generated code yet. Second, AFAIK, such implementation will require us not to add foreign-key constraints because one record can point to different tables - I didn't give it too much attention, but I wonder if there is a better way to implement this. e.g., maybe when there are not too many referenced tables, a column/fk per table is good enough (+ check constraint to ensure only one column is filled). 

Closing because it's a duplicate of https://github.com/ent/ent/issues/1048, but I'd love to continue the discussion on Discord 🙏

**Closed by a8m** 2022-11-27 14:50 UTC
