### ISSUE TITLE
NOT NULL Foreign Key field

### ISSUE THREAD

**Issue by mahmud2011** [ent/ent#1551] opened 2021-05-09 15:52 UTC
```go
// Edges of the TxnSrc.
func (TxnSrc) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("txn_test", TxnTest.Type).
			Required().
			StorageKey(
				edge.Column("txn_src_id"),
				edge.Symbol("fk_txn_test_txn_src_txn_src_id"),
			).Annotations(entsql.Annotation{
			OnDelete: entsql.Restrict,
		}),
	}
}
```

```go
// Fields of the TxnTest.
func (TxnTest) Fields() []ent.Field {
	return []ent.Field{
		field.Uint64("customer_id").
			Immutable(),
	}
}
```

It should make the foreign key field required as the conditions are `Required()` and `entsql.Restrict`.
**Expected:**
```sql
+------------------+---------------------+------+-----+-------------------+----------------+
| Field            | Type                | Null | Key | Default           | Extra          |
+------------------+---------------------+------+-----+-------------------+----------------+
| txn_src_id       | bigint(20) unsigned | NO   | MUL |                   |                |
+------------------+---------------------+------+-----+-------------------+----------------+
```

**Output:**
```sql
+------------------+---------------------+------+-----+-------------------+----------------+
| Field            | Type                | Null | Key | Default           | Extra          |
+------------------+---------------------+------+-----+-------------------+----------------+
| id               | bigint(20) unsigned | NO   | PRI | NULL              | auto_increment |
| customer_id      | bigint(20) unsigned | NO   |     | NULL              |                |
| txn_src_id       | bigint(20) unsigned | YES  | MUL | NULL              |                |
+------------------+---------------------+------+-----+-------------------+----------------+

```

**Comment by a8m** [comment] 2021-05-16 07:48
Hey @mahmud2011 and thanks for reporting this issue.
This is going to be changed in the next version.

Closing, as it's a duplicate of https://github.com/ent/ent/issues/1374. Thanks 🙏

**Closed by a8m** 2021-05-16 07:48 UTC

**Comment by mahmud2011** [comment] 2021-05-16 09:42
_N.B:_ There is also no setter for the `txn_src_id ` field.
