### ISSUE TITLE
AlternateSchema hook: Alter table name

### ISSUE THREAD

**Issue by xcono** [ent/ent#2806] opened 2022-07-27 18:15 UTC
a8m, thanks for the wonderful package!
Now we can use `AlternateSchema` to change the ent's client schema, but what about table names altering?
Is it planned to use `internal.SchemaConfig` to alter the table name? Are there other ways to achieve it (except altering templates)?
I'm trying to reuse one generated entity from my lib for multiple entities with separated tables in client code.

**Comment by a8m** [comment] 2022-07-27 18:27
Hey @xcono and thanks for the kind words. I'm glad you find ent useful 🙏 

This is not supported atm but we can discuss adding this to Ent using a feature flag. Let's follow up on this in https://github.com/ent/ent/issues/1990. 
Closing, as it's a duplicate of https://github.com/ent/ent/issues/1990.

**Closed by a8m** 2022-07-27 18:27 UTC
