### ISSUE TITLE
Question: Is there any way to add property to edge for Gremlin storage?

### ISSUE THREAD

**Issue by seiichi1101** [ent/ent#1783] opened 2021-07-29 10:31 UTC
I'd like to add property to `edge` like blow.

```
gremlin> g.V(1).addE('friend').property('date', 2021)
```

or 

```
gremlin> g.addE('friend').from(g.V(1)).to(g.V(2)).property('date', 2021)
```

**Comment by a8m** [comment] 2021-08-06 12:02
Hey @seiichi1101 and thanks for opening this issue. Currently, there's no way to attach additional fields/properties to edges in all storage engines. However, I'm going to start working on it soon.

Closing as it's a duplicate of https://github.com/ent/ent/issues/1061. Thanks

**Closed by a8m** 2021-08-06 12:02 UTC
