### ISSUE TITLE
go1.19  ent/entc/gen/template/ent.tmpl Unwrap panic is error

### ISSUE THREAD

**Issue by 184104489** [ent/ent#3129] opened 2022-11-29 03:29 UTC
go1.19  
ent v0.11.4
go run entgo.io/ent/cmd/ent generate

ent/entc/gen/template/ent.tmpl 
Unwrap() panic is error

**Comment by a8m** [comment] 2022-11-29 09:56
Hey! I can't reproduce this, so I'll appreciate it if you could create a bug report using https://github.com/ent/bug.

**Comment by a8m** [comment] 2022-12-04 09:40
Closing, but please reopen or join our [Discord](https://discord.gg/qZmPgTE6RX) if you need help and we can support you in this 😃

**Closed by a8m** 2022-12-04 09:40 UTC
