### ISSUE TITLE
sql/migrate/mysql: tables are dropped when system variable lower_case_table_names = 1

### ISSUE THREAD

**Issue by CNTWDev** [ent/ent#3251] opened 2023-01-18 08:10 UTC
ent. v0.11.0
when i have a relationship(followed/following) M2M model.
when i update other schema, then call
`client.Schema.Create(c)`

The intermediate table will always be cleared of data.
The project lost a lot, please help

- [ ] The issue is present in the latest release.
- [ ] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce 🕹

Steps:

1.
2.
3.
4.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16.?  |
| Ent         | 0.11.0?   |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by CNTWDev** [comment] 2023-01-18 08:10
@a8m

**Comment by a8m** [comment] 2023-01-18 08:16
Hey @CNTWDev 👋 
The join table is usually set with `ON DELETE CASCADE` unless something else is configured. I can't think of any case of deleting records in migrations besides dropping one of the parent tables or their primary keys (there are 2 FKs in the join table).

Ent, by default, is dropping columns in migrations unless the `WithDropColumn` option is enabled. Tables are never dropped as well. So, I can't think of how migration can cause record deletions. Would you mind sharing more information, logs, or anything that can help to understand this better?

**Comment by a8m** [comment] 2023-01-18 08:17
Hey @CNTWDev 👋 
The join table is usually set with `ON DELETE CASCADE` unless something else is configured. I can't think of any case of deleting records in migrations besides dropping one of the parent tables or their primary keys (there are 2 FKs in the join table).

Ent, by default, is **not** dropping columns in migrations unless the `WithDropColumn` option is enabled. Tables are never dropped as well. So, I can't think of how migration can cause record deletions. Would you mind sharing more information, logs, or anything that can help to understand this better?

**Comment by CNTWDev** [comment] 2023-01-18 08:21
Configrations:
ent generate command:
`go run entgo.io/ent/cmd/ent generate --feature privacy,entql,sql/upsert ./ent/schema`

Create or Update command:
`client := model.DBClient
	//ctx := context.Background()
	//defer client.Close()
	if err := client.Schema.Create(c); err != nil {
		logger.W.Error("failed creating schema resources:" + err.Error())
		Res.FailedWithErrno(c, e.ERR_DATABASE, err.Error())
		return
	}`

Account Schema:
`func (Account) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("account_gg", Google.Type).Unique(),
		edge.To("account_fb", Facebook.Type).Unique(),
		edge.To("records", Record.Type),
		edge.To("accountFollow", Accountchurch.Type),
		edge.To("account_fcm", Fcm.Type),
		edge.To("contact", Contact.Type).Unique(),
		edge.To("profile", Profile.Type).Unique(),
		edge.To("mood", Mood.Type).Unique(),
		edge.To("db_verse", Db_verse.Type),
		edge.To("db_devotion", Db_devotion.Type),
		edge.To("db_highlights", Db_highlights.Type),
		edge.To("db_notes", Db_notes.Type),
		edge.To("db_bookmarks", Db_bookmarks.Type),
		edge.To("db_date_log", Db_date_log.Type),
		edge.To("hasFriend", Account.Type).From("preFriend"),//The intermediate table will be cleared
		edge.To("church_draft", ChurchDraft.Type),
		edge.To("creator", Church.Type),
		edge.To("googlemap", GoogleMap.Type),
		// sync v2.0
		edge.To("user_mark", UserMark.Type),
		edge.To("user_note", UserNote.Type),
		edge.To("user_highlight", UserHighlight.Type),
		edge.To("user_quiz", UserQuizRecord.Type),
	}`
database table：
![image](https://user-images.githubusercontent.com/53957246/213119868-15e0151c-00b9-4ef6-ac21-ac900ab73993.png)

**Comment by CNTWDev** [comment] 2023-01-18 08:23
Sorry, i don't know how to get the log created by framework ent.

but when i run Schema.create,it goes well without any error.

**Comment by a8m** [comment] 2023-01-18 08:26
Try running the client with `client = client.Debug()`.

**Comment by CNTWDev** [comment] 2023-01-18 08:38
It cannot be reproduced in the development environment.
The debug log of the production environment cannot be obtained.

How can i do? Thanks

**Comment by CNTWDev** [comment] 2023-01-18 08:47
In the production environment, I just tried it, and the data is cleared every time.

@a8m

**Comment by a8m** [comment] 2023-01-18 08:47
Try to check; maybe you renamed some edges/nodes and got a different (another) join table? The `git log` command on the `ent/migrate/schema.go` should show this or "show tables" on the specific schema in MySQL. 

> In the production environment, I just tried it, and the data is cleared every time.

Try to run this with `client.Debug()` and reports the logs (here or privately on Discord).

**Comment by CNTWDev** [comment] 2023-01-18 08:50
Schema.Create is called multiple times and cleared multiple times.
If other tables are restructured, the table data will not be cleared every time.
Is my understanding correct?

**Comment by CNTWDev** [comment] 2023-01-18 08:58
![image](https://user-images.githubusercontent.com/53957246/213127512-0a05c99c-d188-4fcf-a1b1-b4c8877cb330.png)

**Comment by a8m** [comment] 2023-01-18 09:11
Hey! Thanks for the schema, but it does not help me. Try to follow this:

> Try to check; maybe you renamed some edges/nodes and got a different (another) join table? The `git log` command on the `ent/migrate/schema.go` should show this or "show tables" on the specific schema in MySQL.
> 
> > In the production environment, I just tried it, and the data is cleared every time.
> 
> Try to run this with `client.Debug()` and report please the logs (here or privately on Discord).

**Comment by CNTWDev** [comment] 2023-01-18 09:26
> Hey! Thanks for the schema, but it does not help me. Try to follow this:
> 
> > Try to check; maybe you renamed some edges/nodes and got a different (another) join table? The `git log` command on the `ent/migrate/schema.go` should show this or "show tables" on the specific schema in MySQL.
> > > In the production environment, I just tried it, and the data is cleared every time.
> > 
> > 
> > Try to run this with `client.Debug()` and report please the logs (here or privately on Discord).

"Try to run this with `client.Debug()` and report please the logs (here or privately on Discord)."

maybe,It looks like the log for this step is a bit more accurate, I struggled to print it out.

**Comment by a8m** [comment] 2023-01-18 09:58
OK. Let me know if there's anything specific I can help with this, please.

As mentioned above, since migrations should not delete any records (or drop columns) unless you configured this, I suspect that you may renamed the edge that caused a new join table to be created, and the old one is still there: the way to check this is to see the previous versions of the `ent/migrate/schema.go` (using git) or check if there are any other tables in your database that are not presented in: `ent/migrate/schema.go`.

Also, I'll recommend you to check out the versioned migration option in Ent: https://entgo.io/docs/versioned-migrations, or run the automatic migration with dry-run mode on your database before executing the migration, in case you configured it with DropIndex or DropColumn, see: https://entgo.io/docs/migrate#offline-mode.

**Comment by a8m** [comment] 2023-01-18 10:10
> Schema.Create is called multiple times and cleared multiple times.
> If other tables are restructured, the table data will not be cleared every time.
> Is my understanding correct?

@CNTWDev, can you elaborate on what you mean by this? 
- How many times have you run `Schema.Create`?
- What do you mean tables are restructured? Internally by MySQL or something else?

**Comment by masseelch** [comment] 2023-01-18 10:33
Hey @CNTWDev, I tried to reproduce your issue, but was not successful in doing so. Please find below the schema and instructions I used. If you could help me reproduce the exact steps you took when you experienced the data loss, I can triage more and hopefully find what caused this. In the meantime, what was the exact change you did? Did you possibly rename `Account`? Was is named `User` before?

```
// schema.go
type User struct {
	ent.Schema
}

func (User) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").
			Unique(),
		field.Int("age"),
	}
}

func (User) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("hasFriend", User.Type).From("preFriend"),
	}
}
```

```
// triage_test.go
func Test(t *testing.T) {
	ctx := context.Background()

	client, err := ent.Open(dialect.MySQL, "root:nopass@tcp(localhost:3306)/fix3251")
	require.NoError(t, err)
	require.NoError(t, client.Schema.Create(ctx))

	// Create some records in the intermediate table.
	u1 := client.User.Create().SetName("a8m").SaveX(ctx)
	u2 := client.User.Create().SetName("masseelch").AddHasFriend(u1).SaveX(ctx)

	// Check they indeed to exist.
	require.True(t, u1.QueryPreFriend().ExistX(ctx))
	require.True(t, u2.QueryHasFriend().ExistX(ctx))

	// Make a change to schema dn run migration tool.
	client2, err := ent2.Open(dialect.MySQL, "root:nopass@tcp(localhost:3306)/fix3251")
	require.NoError(t, err)
	require.NoError(t, client2.Schema.Create(ctx))

	// Check records still exist.
	require.True(t, client2.User.Query().Where(user2.ID(1)).QueryPreFriend().ExistX(ctx))
	require.True(t, client2.User.Query().Where(user2.ID(2)).QueryHasFriend().ExistX(ctx))
}
```

**Comment by CNTWDev** [comment] 2023-01-18 10:43
@a8m what's the discord channel? thanks.

**Comment by masseelch** [comment] 2023-01-18 10:44
https://discord.gg/qZmPgTE6RX

> @a8m what's the discord channel? thanks.

**Comment by a8m** [comment] 2023-01-19 13:45
Following our discussion on Discord, this was fixed with https://github.com/ariga/atlas/pull/1410 and https://github.com/ent/ent/pull/3253.

A new tag was added: v0.11.6. Please, try this and let me know if you still have trouble with it. Note you can run MySQL with the same system variable as follows:

```console
docker run -d --rm --name ent-test -p 3306:3306 \
  -e MYSQL_ROOT_PASSWORD=pass -e MYSQL_DATABASE=test \
  mysql:8.0.29 mysqld --lower_case_table_names=1
```

**Closed by a8m** 2023-01-19 13:45 UTC

**Comment by a8m** [comment] 2023-01-19 13:47
Also, I forgot to say - thanks for helping us troubleshoot this issue. It's appreciated 🙏

**Comment by CNTWDev** [comment] 2023-01-19 15:14
You are welcome, Ent helps me to build a stable golang program efficiently.  Hope it helps the ent team.
