### ISSUE TITLE
create entities from existing database

### ISSUE THREAD

**Issue by dara-na** [ent/ent#1285] opened 2021-03-01 07:30 UTC
is there any way to create entities from the existing database?
I think that would be really great for migrating existing microservices with different DB access layers to ent
a quick example would be adding a connection-string switch to ent cmd and ent cmd reads the schema from provided connection and generates all entities from the schema :

ent generate --connection-string="root:pass@tcp(localhost:3306)/test"

**Comment by rotemtam** [comment] 2021-03-05 09:01
Hey @dara-na 
This has been discussed before on #967. Speaking with @a8m , there are some plans to add something like this to ent (directly or through an auxiliary tool), but currently no established timeline for that.

**Comment by a8m** [comment] 2021-03-05 10:31
Hey @dara-na and thanks @rotemtam for tagging me. I missed this issue.
I updated in our [Slack channel](https://app.slack.com/client/T029RQSE6/C01FMSQDT53) that a new [schema inspection](https://pkg.go.dev/entgo.io/ent@v0.6.0/dialect/sql/schema#Inspector) API was added to the framework, and the next step is to generate `ent.Schema` from it. 

Closing this issue because this is a duplicate of #967, but I'll update this issue when this capability is added to ent.
Thanks and sorry for the delayed response.

**Closed by a8m** 2021-03-05 10:31 UTC

**Comment by dara-na** [comment] 2021-03-05 10:36
I think this will help a lot for systems in production
Because this is really painful to migrate existing schemas manually to ent

**Comment by a8m** [comment] 2021-03-05 10:51
Totally agree @dara-na. Please join our Slack channel and I'll ping you when I have some progress on it. It would be great to get feedback on early stage. Thanks
