### ISSUE TITLE
cant resolve same package name with different import path in generated code

### ISSUE THREAD

**Issue by washanhanzi** [ent/ent#1565] opened 2021-05-17 17:19 UTC
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

If I have two package with same name, but different path, ent can't resolve them correctly in generated code.

## Expected Behavior 🤔

Maybe ent can 'magically' resolve them with different import names, or report the conflict package names to let the user define different import names.

## Steps to Reproduce 🕹

https://github.com/washanhanzi/ent-same-package-name

The problem is in [mutation.go](https://github.com/washanhanzi/ent-same-package-name/blob/main/ent/mutation.go) and [runtime.go](https://github.com/washanhanzi/ent-same-package-name/blob/main/ent/runtime.go)

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16.?  |
| Ent         | 0.8.0   |

**Comment by a8m** [comment] 2021-05-19 12:20
Hey @washanhanzi and thanks for opening this issue.

I was able to reproduce this, however, the change is not so simple, because there's no way to get the "import alias" (e.g. `import name "<path>"`) using reflection. 

I'll try to think on some workaround for this and will update this issue.

**Comment by ben181231** [comment] 2021-11-04 08:44
Hello @a8m. I also faced this issue. May I know any updates on this issue?

**Comment by medivh-jay** [comment] 2021-11-22 07:05
Hello @a8m . I have the same problem. at present, the only solution is to change the name of the package. are there any other plans?

Is it feasible to design like this?

```
type Package interface {
    Packages() []pkg.Package 
}
```

implement the `Package`

```
func (xxx) Packages() []ent.Package  {
    return []ent.Package{
        pkg.Import("github.com/a/b").Alias("AB"), // import AB "github.com/a/b"
    }
}
```

**Comment by AdlerShay** [comment] 2022-02-01 14:46
Hi @a8m , having the same problem, only that I'm using an external package which I can't rename. Is there any update on this one?

**Comment by a8m** [comment] 2022-02-02 13:50
Hey all 👋
Sorry for the delay, the issue was not really urgent (for my case), and I was working on other stuff.

I landed a patch that should solve this issue. See #1565

Basically, the code-generator detects if the local names of the generated packages (`gen.Type`) conflict with a local name of any of the user-defined types. In case of a conflict, it adds a different local name (an alias) to be used by the generated `ent` package. e.g. for `"ent/pet"` the new local name will be `entpet "ent/pet"`.

One of the options we discussed internally before was to use the "alias" (alternative local name) used in the `ent/schema` for user-defined `GoType`s, but decided not as the same type can be imported differently in the same ent/schema (multiple files).

Closing, but please let me know if you have any troubles with it. Thanks for reporting this @washanhanzi 🙏 ❤️

**Closed** 2022-02-02 13:50 UTC
