### ISSUE TITLE
Polymorphic JSON field

### ISSUE THREAD

**Issue by kpeu3i** [ent/ent#2491] opened 2022-04-23 08:53 UTC
Hi, guys! I have a question about defining the JSON field which stores different structures depending on the entity type.

I know that I can define JSON like this:
```
field.JSON("data", Data{})
```

But in my case, I need to have something like that:
```
field.JSON("data", Data1{})
field.JSON("data", Data2{})
field.JSON("data", Data3{})
```
because different structs are stored inside the data field.

So, is it possible somehow to choose the correct data structure when scanning the JSON field based on another field value from the entity (e.g type)?

**Comment by a8m** [comment] 2022-04-25 10:31
Hey @kpeu3i and thanks for opening this issue 👋 

You can use a custom type that implements the [json.Marshaler](https://pkg.go.dev/encoding/json#Marshaler)/[json.Unmarshaler](https://pkg.go.dev/encoding/json#Unmarshaler) interfaces, store a field named `Data` (an interface type) and decide on the decoding stage what type to assign to it.

For example, for a field `field.JSON("addr", Addr{})` that can hold multiple variants of "net addresses", I'll implement it as follows: 

```go

type Addr struct{ net.Addr }

func (a *Addr) UnmarshalJSON(data []byte) error {
	var types struct {
		TCP *net.TCPAddr `json:"tcp,omitempty"`
		UDP *net.UDPAddr `json:"udp,omitempty"`
	}
	if err := json.Unmarshal(data, &types); err != nil {
		return err
	}
	switch {
	case types.TCP != nil && types.UDP != nil:
		return errors.New("TCP and UDP addresses are mutually exclusive")
	case types.TCP != nil:
		a.Addr = types.TCP
	case types.UDP != nil:
		a.Addr = types.UDP
	}
	return nil
}

func (a Addr) MarshalJSON() ([]byte, error) {
	var types struct {
		TCP *net.TCPAddr `json:"tcp,omitempty"`
		UDP *net.UDPAddr `json:"udp,omitempty"`
	}
	switch a := a.Addr.(type) {
	case *net.TCPAddr:
		types.TCP = a
	case *net.UDPAddr:
		types.UDP = a
	default:
		return nil, fmt.Errorf("unsupported address type: %T", a)
	}
	return json.Marshal(types)
}
```

I also added an example PR for your use-case in this repository, please give it a look https://github.com/ent/ent/pull/2497

Closing, but please feel free to reopen or join our [Discord server](https://discord.gg/qZmPgTE6RX) if you still need help with this.

**Closed** 2022-04-25 10:34 UTC
Labels: Question

**Comment by kpeu3i** [comment] 2022-04-25 10:52
@a8m thanks for your response. I got your idea. But I'm trying to switch to Ent from an existing database and I cannot modify the data structure that is stored inside the `data` column. 

In terms of your example, `*net.TCPAddr` and `*net.UDPAddr` are stores in my DB without wrapper struct `types`, so I cannot detect which struct should be used when unmarshaling bytes.

The only way to detect which struct is the value of `type` column from the parent entity. So, I'm wondering is it possible somehow access other entity field values when scanning a value for the field? Seems like it should be possible inside the  generated method `assignValues` method

**Comment by a8m** [comment] 2022-04-25 11:32
I think another nice solution for this is to use `field.JSON("data", json.RawMessage{})` to store the field raw, and expose a method on the type `T` like `ParseData() Data` that can access the `type` and the `data` fields and can return you a parsed version of it. Same thing for Marshaling.

These fields can be added using custom templates or manually in an `ent/custom.go` file. 

We can expose an API for calling custom functions in `assignValues`, but I need to think of a clean API for this. I'd expect something like this to reside on the field-level but the issue is that you need access to another field

**Comment by a8m** [comment] 2022-04-25 11:33
hehe, @masseelch 😆 

@hedwigz and I just discussed this and we both commented this at the same time :)
