### ISSUE TITLE
Execution results of query generated by ent and results retrieved by ent are different

### ISSUE THREAD

**Issue by yootaki** [ent/ent#3679] opened 2023-08-05 07:04 UTC
I have tried to retrieve data using Modify, but it does not return the expected results.
I have tried using Debug() to check the result query and run it in MySQL, in which case it returns the expected results.
Is there any possible cause for this?

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Example
Using the following as an example:
```
repository.Client.User.Query().
		Modify(func(s *sql.Selector) {
			t1 := sql.Table(shift.Table)
			s.LeftJoin(t1).OnP(
				sql.And(
					sql.EQ(s.C(user.FieldID), t1.C(shift.FieldUserID)),
					sql.GTE(t1.C(shift.AttenadanceDate), now),
				),
			).
				GroupBy(s.C(user.FieldID)).
				OrderBy(
					sql.Asc(sql.Min(t1.C(shift.AttenadanceDate))+" IS NULL"),
					sql.Asc(sql.Min(t1.C(shift.AttenadanceDate))),
					sql.Desc(s.C(user.FieldID)),
				)
		}).All(ctx)
```
The resulting query looks like this:
```
SELECT
	DISTINCT `users`.`id`,
	`users`.`name`,
FROM
	`users`
LEFT JOIN `shifts` AS `t1` ON
	`users`.`id` = `t1`.`user_id`
	AND `t1`.`attendance_date` >= '2023-08-05 05:42:56'
GROUP BY
	`user_follows`.`target_user_id`
ORDER BY
	MIN(`t1`.`attendance_date`) IS NULL ASC,
	MIN(`t1`.`attendance_date`) ASC,
	`users`.`id` DESC;
```

## Expected Behavior
I assume that I can get results sorted by `MIN(t1.attendance_date) ASC` and `users.id DESC`, but in reality I get only results sorted by `users.id DESC`.

**Comment by a8m** [comment] 2023-08-05 07:12
Hey @yootaki 👋 

It looks like the generated SQL query matches the ent query created by the builder. I can't really tell what causes your unexpected behavior, but it does not look like the issue is on the builder's side. 

Closing, but you are welcome to join our [Discord community](https://discord.gg/qZmPgTE6RX) and ask for help from MySQL users. Thanks 😎

**Closed by a8m** 2023-08-05 07:12 UTC

**Comment by robertjpeters** [comment] 2023-09-20 19:50
@yootaki 
I ran into this exact issue and can add some details:

The problem lies here
`sql.EQ(s.C(user.FieldID), t1.C(shift.FieldUserID)),`

As you're comparing columns to each other, you need to use
`sql.ColumnsEQ(s.C(user.FieldID), t1.C(shift.FieldUserID)),`

sql.EQ -> sql.ColumnsEQ

What's interesting here is that .Debug() **produces the SAME query for both, but is NOT executing the same query**.
