### ISSUE TITLE
Want to avoid internal/schema.go conflicts when developing in multiple branches.

### ISSUE THREAD

**Issue by yuki2006** [ent/ent#3240] opened 2023-01-13 14:30 UTC
Thank you for the ent libs.

- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

When developing on multiple branches, schema changes in branches often git conflict in internal/schema.go.

I suspect this is because `const Schema =` is a single line.
Maybe, this could be worked around by making it multiple lines or multiple files.

## Motivation 🔦

For changes in the schema of another branch that have no effect, I would like to avoid redoing the code generation.

**Comment by yuki2006** [comment] 2023-01-14 10:26
@khanakia 

thx comments.

I'd like to keep `schema/snapshot` feature enabled for development flow.

Other code can be automatically merged, but `ent/internal/schema.go` may not automatically merge.

https://github.com/yuki2006/ent_branch_test/pull/2


<img width="869" alt="image" src="https://user-images.githubusercontent.com/1004620/212467452-a491e368-b73e-4b4c-8f13-a6c4bb905e76.png">

**Comment by a8m** [comment] 2023-01-14 10:31
The all point of the `Schema`  variable is to be the conflict point. If you run `go generate` Ent will solve this conflict and generate the new assets. The only conflicts you need to solve by yourself are changes in the `ent/schema` package .

**Comment by yuki2006** [comment] 2023-01-14 11:06
@a8m 
Thanks, that's true.

I would expect the spec to be changed if possible.

Maybe it's not recommended in `ent`, but our project doesn't manage auto-generated files in git.

(I wish I could prevent auto-generated files from showing up in the GitHub changelist because it would interfere with code review...)

In the case of our project, if the schema/snapshot can be merged automatically, that's good enough in practice..

**Comment by a8m** [comment] 2023-01-16 09:15
You get the conflict because there are changes in the master branch that your PR is not rebased on. In this case, you need to pull the changes and rerun the codegen, because they may cause a different assets generation. This can also be risky if you use versioned migration or just have incorrect code in the generated clients/builders (it relies on git the auto-merge). i.e., that's a feature, not a bug 😃 

Closing, but you're welcome to join our [Discord community](https://discord.gg/qZmPgTE6RX) and we can continue the discussion there 😎

**Closed by a8m** 2023-01-16 09:15 UTC
