### ISSUE TITLE
creating seeds file the output result is unexpected

### ISSUE THREAD

**Issue by tomoyukikino** [ent/ent#3505] opened 2023-04-27 06:31 UTC
I'm creating a migration seed file.
And the DDL is not the expected format.
I'm create this seed code.

```go
package migratedata

import (
	"context"
	"fmt"
	"time"

	"ariga.io/atlas/sql/migrate"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql/schema"
	"github.com/bilbase-inc/maruki_back/ent"
)

// SeedData add the initial users to the database.
func SeedData(dir *migrate.LocalDir, suffix string) error {

	n := time.Now()
	w := &schema.DirWriter{Dir: dir}
	client := ent.NewClient(ent.Driver(schema.NewWriteDriver(dialect.MySQL, w)))

	// Insert into master data.
	err := client.MstSupplierImportance.CreateBulk(
		client.MstSupplierImportance.Create().SetRank("A").SetCreatedAt(n).SetUpdatedAt(n),
		client.MstSupplierImportance.Create().SetRank("B").SetCreatedAt(n).SetUpdatedAt(n),
		client.MstSupplierImportance.Create().SetRank("C").SetCreatedAt(n).SetUpdatedAt(n),
	).Exec(context.Background())
	if err != nil {
		return fmt.Errorf("failed generating statement: %w", err)
	}

	err = client.MstQuotationImportance.CreateBulk(
		client.MstQuotationImportance.Create().SetRank("A"),
		client.MstQuotationImportance.Create().SetRank("B"),
		client.MstQuotationImportance.Create().SetRank("C"),
	).Exec(context.Background())
	if err != nil {
		return fmt.Errorf("failed generating statement: %w", err)
	}

	err = client.MstQuotationMethodPriority.CreateBulk(
		client.MstQuotationMethodPriority.Create().SetLabel("○"),
		client.MstQuotationMethodPriority.Create().SetLabel("△"),
		client.MstQuotationMethodPriority.Create().SetLabel("☓"),
	).Exec(context.Background())
	if err != nil {
		return fmt.Errorf("failed generating statement: %w", err)
	}

	// Write the content to the migration directory.
	name := "seed_" + suffix
	return w.FlushChange(
		name,
		"Add the initial master data to the database.",
	)
}
```

So I cannot apply seed by atlas.

- [x ] The issue is present in the latest release.
- [x ] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.
I found this similar issue https://github.com/ent/ent/issues/3362 but not solve.

## Current Behavior 😯

The above seed file generate below sql .
`{{ TIME_VALUE }}` is bug.
```sql
-- Add the initial master data to the database.
INSERT INTO `mst_supplier_importances` (`created_at`, `rank`, `updated_at`) VALUES ({{ TIME_VALUE }}, 'A', {{ TIME_VALUE }}), ({{ TIME_VALUE }}, 'B', {{ TIME_VALUE }}), ({{ TIME_VALUE }}, 'C', {{ TIME_VALUE }});
INSERT INTO `mst_quotation_importances` (`created_at`, `rank`, `updated_at`) VALUES ({{ TIME_VALUE }}, 'A', {{ TIME_VALUE }}), ({{ TIME_VALUE }}, 'B', {{ TIME_VALUE }}), ({{ TIME_VALUE }}, 'C', {{ TIME_VALUE }});
INSERT INTO `mst_quotation_method_priorities` (`created_at`, `label`, `updated_at`) VALUES ({{ TIME_VALUE }}, '○', {{ TIME_VALUE }}), ({{ TIME_VALUE }}, '△', {{ TIME_VALUE }}), ({{ TIME_VALUE }}, '☓', {{ TIME_VALUE }});
```

## Expected Behavior 🤔

It need to remove `created_at` and `update_at` column from `INSERT INTO` clause column list.

```sql
-- Add the initial master data to the database.
INSERT INTO `mst_supplier_importances` (`rank`) VALUES ('A'), ('B'), ('C');
INSERT INTO `mst_supplier_importances` (`rank`) VALUES ('A'), ('B'), ('C');
 INSERT INTO `mst_supplier_importances` (`rank`) VALUES ('○'), ('△'), ('☓');
```

## Steps to Reproduce 🕹

Steps:

1. run `$ go run -mod=mod ent/migrate/main.go fuga`
2. gen `20230427060509_seed_fuga.sql`
3. run `$ atlas migrate apply --dir file://ent/migrate/migrations --url mysql://root:pass@localhost:3306/test`
4. below error is happen in atlas
```bash
 Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '{ TIME_VALUE }}, 'A', {{ TIME_VALUE }}), ({{ TIME_VALUE }}, 'B', {{ TIME_VALUE }' at line 1
```

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19  |
| Ent         | v0.12.2   |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by a8m** [comment] 2023-04-27 12:49
Hey, @tomoyukikino 👋 

Please, see my comment on https://github.com/ent/ent/issues/3362#issuecomment-1454872165. Closing, as this is a duplicate of #3362 and has been answered. Feel free to join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎

**Closed by a8m** 2023-04-27 12:49 UTC
