### ISSUE TITLE
`.Paginate(ctx)` return empty `Edges` if called from dataloaders

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2679] opened 2022-06-23 12:53 UTC
## Current Behavior 😯

[I thought it was another problem](https://github.com/ent/ent/issues/2676) but now I understood that if the below query is called by another one it returns empty `.Edges`:

```go
func PlayersQuery(
  ctx context.Context,
  input app.PlayersInput,
) (*ent.PlayerConnection, error) {
  query := db.Player.Query()

  query.Where(entPlayer.TrackableType("TRACKABLE_TYPE_NAME"))

  res, err := query.Paginate(
    ctx, // context.background() works!
    nil, nil, nil, nil
  )
  // handle err

  return res, nil
}
```

If I use `query.Paginate(context.background())` **it works!**

If I don't use `.Paginate()` and use `.All()` it works.

I'm calling the second query from dataloaders.

Maybe the second call to `Paginate()` has issues with that `context`?

## Your Environment 🌎

| Tech     | Version                                                                                                   |
| -------- | --------------------------------------------------------------------------------------------------------- |
| Go       | 1.18.3                                                                                                    |
| Ent      | entgo.io/contrib v0.2.1-0.20220623093601-df0921394080, entgo.io/ent v0.10.2-0.20220622152053-3bb5292c83bf |
| Database | PG                                                                                                        |
| Driver   | pgx                                                                                                       |

**Comment by frederikhors** [comment] 2022-06-23 13:00
@a8m answered on discord:
> gqlgen attaches the query metadata on the context, and entgql uses fields collection using the gqlgen API.
> If nothing was requested by the gql query, query is not executed

**Comment by frederikhors** [comment] 2022-06-23 13:03
I think this is really a bad situation because the second `.Paginate()` is called by dataloaders not directly by gqlgen. And in the context there is the "first" gqlgen metadata.

Am I right?

**Comment by frederikhors** [comment] 2022-06-23 13:48
The dataloader I'm using is like this:

```go
func (o *loaders) TeamsByPlayerIDs(ctx context.Context, keys dataloader.Keys) []*dataloader.Result {
	keyOrder := make(map[uint64]int, len(keys))

	keyIDs := make([]uint64, len(keys))

	for i := range keys {
		keyID, err := strconv.ParseUint(keys[i].String(), 10, 64)
		//handle err

		keyIDs[i] = keyID
		keyOrder[keyID] = i
	}

	records, err := TeamListByPlayerIDs.Handle(ctx, app.TeamListInput{}, keyIDs)
	//handle err

  // here records.Edges is empty

	results := make([]*dataloader.Result, len(keys))

	for i := range records.Edges {
		//add records to results here
	}

	return results
}
```

I don't think there is something broken with it.

**Comment by giautm** [comment] 2022-06-23 13:53
> records, err := TeamListByPlayerIDs.Handle(ctx, app.TeamListInput{}, keyIDs)

How do you implement the Handle function?

PS: You may not need to use dataloader with EntGQL, because Ent already optimize for N+1 issue.

**Comment by a8m** [comment] 2022-06-23 14:50
May I ask what happens if you call `All` instead of `Paginate`?

**Comment by frederikhors** [comment] 2022-06-23 14:54
The problem is with `paginate()` only.

**Comment by giautm** [comment] 2022-06-23 16:08
> The problem is with `Paginate()` only.

I think `Paginate()` was designed to work best with the EntGQL extension. It's based on the context from GQLgen to preloads edges.

If you can share more detail about your use-cases (In the private talk) I think we can help more.

**Comment by frederikhors** [comment] 2022-06-23 17:57
> In the private

With all the NDA I think it's impossible. In a few days I can recreate a complete repro with gqlgen and dataloaders.

**Comment by frederikhors** [comment] 2022-06-23 20:46
> PS: You may not need to use dataloader with EntGQL, because Ent already optimize for N+1 issue.

Guys, am I correct in saying that when I call `Paginate()` ent eager loads the edges required by the graphql query, but if for example I'm using a query with `.First()` I have to manually call `.CollectFields()`?

To be more specific, I'm trying to remove all the manual resolvers from gqlgen.yml, example:

```yml
models:
  Player:
    fields:
      team:
        resolver: true
      game:
        resolver: true
      season:
        resolver: true
      coach:
        resolver: true
```

If I'm querying with:

```go
que := repo.Player.Query()

output, err := que.Paginate(
  ctx,
  After,
  First,
  Before,
  Last,
  //others...
)
```

Ent correctly (and amazingly) eager-loads `team`, `game`, `season`, `coach` if requested in the query.

But I just found out that if I query with `First()` it doesn't:

```go
que := repo.Player.Query().Where(player.ID(id))

output, err := que.First(ctx)
```

I tried adding `que.CollectFields(ctx)` and it worked.

**I just wanna know if this is the correct "way" to use it.**

**Comment by a8m** [comment] 2022-06-23 20:54
You're right. `entgql` does not change the base templates of Ent and that's why fields collection is not enabled in `First` or `All`. However, you can call `CollectFields` as you mentioned, or just call paginate with `first` set to 1. I hope it helps.

**Comment by a8m** [comment] 2022-06-24 06:39
I think we can close this issue. Please, feel free to reopen if you find anything in Ent.

Thanks ❤️

**Closed by a8m** 2022-06-24 06:39 UTC
