### ISSUE TITLE
entc confused when GoType referenced value's package name doest not match directory name

### ISSUE THREAD

**Issue by joesonw** [ent/ent#1507] opened 2021-04-25 15:02 UTC
When I was using GoType to reference a value in another package, where the directory name and package name does not match, it will not generate correct code

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

imports messesd up

## Expected Behavior 🤔

imports right

## Steps to Reproduce 🕹

There is a file located at `example.com/pbgo/player/v1/status.pb.go`
```go
package player_pb

type Status struct {

}
```

and reference it in ent schema file: `example.com/ent/user.go`
```go

import player_pb "example.com/pbgo/player/v1"

type User struct {
    ent.Schema
}

func (User) Fields() []ent.Field {
    return []ent.Field{
        field.JSON("status", player_pb.Status{}),
    }
}

```

it will generate something like below (only parts of code where went wrong):
```go
import (
    	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"  // AND HERE
)

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldStatus:
			values[i] = new(v1.Status) // HERE
		default:
			return nil, fmt.Errorf("unexpected column %q for type User", columns[i])
		}
	}
	return values, nil
}

```

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16.?  |
| Ent         | 0.8.?   |
| Database    | Mysql   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by a8m** [comment] 2021-04-25 15:09
Thanks for reporting this @joesonw. I'll give it a look

**Comment by a8m** [comment] 2021-04-25 15:55
@joesonw - I'm not able to reproduce this. Can you please try to update ent to the latest master and re-run codegen?

```
go get -u entgo.io/ent@master
```

If it still happens, can you please share an example (in a GitHub repo) so I can reproduce this?

**Comment by joesonw** [comment] 2021-04-26 03:03
@a8m sorry for the delay. but I've managed to come with an example here, https://github.com/joesonw/ent-issue-1507. the file with problem is here https://github.com/joesonw/ent-issue-1507/blob/master/ent/user.go

thank you

**Comment by a8m** [comment] 2021-04-26 13:58
Thanks for the example @joesonw. The issue was fixed with #1511

**Closed** 2021-04-26 13:57 UTC

**Comment by joesonw** [comment] 2021-04-26 14:56
@a8m Thank you !!! It is working as expected now.

**Comment by a8m** [comment] 2021-04-26 19:03
Sure, happy to help! Thanks for the informative issue!

Also, you're welcome to join our [Slack channel](https://app.slack.com/client/T029RQSE6/C01FMSQDT53) in the Gophers Slack and if you're interested to get ~monthly updates on our new releases and features, subscribe to our [newsletter](https://www.getrevue.co/profile/ent) 🙏 

@all-contributors please add @joesonw for bug report.
