### ISSUE TITLE
field.json doesn't support array struct ?

### ISSUE THREAD

**Issue by dybxin** [ent/ent#1426] opened 2021-04-06 05:00 UTC
in schema, i definition an []struct{}:

```go
func (Scene) Fields() []ent.Field {
  return []ent.Field{
   field.String("name"),                  
   field.String("remark").Optional(),
   field.JSON("times", []struct {
      Start string `json:"start"`
      End   string `json:"end"`
    }{}).Optional(), // in time period
 }
}
```

in main.go file

```go
type Comparator struct {
  Name string `json:"name"`
  Remark      string `json:"remark"`
  Times          []struct {
    start string `json:"start"`
    end   string `json:"end"`
  } `json:"times"`
}

when i use `ctrl.DB.Comparator.Create().SetTimes(item.Times)` to setTimes, i got prompt `cannot use 'item.Times' (type []struct{...}) as type []struct{...}`

the details: cannot use item.Times (type []struct { start string "json:\"start\""; end string "json:\"end\"" }) as type []struct { Start string "json:\"start\""; End string "json:\"end\"" } in argument to tx.Scene.Create().SetName(sceneModel.Name).SetRemark(sceneModel.Remark).SetTimes
```

**Comment by a8m** [comment] 2021-04-06 05:21
Hey @dybxin and thanks for opening this issue.
Can you please use a named type in your schema and reports if you still get this error:

```go
type Time struct { Start, End string }

field.JSON("times", []Time)
```

**Comment by dybxin** [comment] 2021-04-06 05:34
> Hey @dybxin and thanks for opening this issue.
> Can you please use a named type in your schema and reports if you still get this error:
> 
> ```go
> type Time struct { Start, End string }
> 
> field.JSON("times", []Time)
> ```

the `field.JSON("times", []Time)` is should be `field.JSON("times", []Time{})`?

**Comment by dybxin** [comment] 2021-04-06 05:40
@a8m i use the fllowing

```go
type Time struct { Start, End string }

field.JSON("times", []Time{})
```

the error is still occured.

**Comment by a8m** [comment] 2021-04-06 06:54
> the `field.JSON("times", []Time)` is should be `field.JSON("times", []Time{})`?

Yes.

It works for me without any problems. Can you please provide an example repository with `ent/schema` that I can reproduce this? Also, what ent version do you use?

**Comment by dybxin** [comment] 2021-04-06 14:59
the ent/schema  scene.go
```go
package schema

import (
  "entgo.io/ent"
  "entgo.io/ent/schema/edge"
  "entgo.io/ent/schema/field"
)

// Scene holds the schema definition for the Scene entity.
type Scene struct {
  ent.Schema
}

func (Scene) Mixin() []ent.Mixin {
  return []ent.Mixin{
    BaseMixin{},
  }
}

func (Scene) Fields() []ent.Field {
  return []ent.Field{
    field.String("name"),
    field.String("remark").Optional(),
    field.Bool("enabled").Default(false), 
    field.String("violation_desc").Optional(),
    field.String("comparator"),
    field.String("label").Optional(),
    field.JSON("zone", struct {
      X1 float64 `json:"x1"`
      Y1 float64 `json:"y1"`
      X2 float64 `json:"x2"`
      Y2 float64 `json:"y2"`
    }{}).Optional(),
    field.Float("ratio_threshold").Optional(),
    field.JSON("times", []struct {
      Start string `json:"start"`
      End   string `json:"end"`
    }{}).Optional(), 
    field.Int("trigger_threshold"), 
    field.Int("inspect_minuts"),
  }
}

// Edges of the Scene.
func (Scene) Edges() []ent.Edge {
  return nil
}
```

the  BaseMixin 

```go
package schema

import (
  "entgo.io/ent"
  "entgo.io/ent/schema/field"
  "entgo.io/ent/schema/index"
  "entgo.io/ent/schema/mixin"
  "github.com/rs/xid"
  "time"
)

type BaseMixin struct {
  // We embed the `mixin.Schema` to avoid
  // implementing the rest of the methods.
  mixin.Schema
}

func (BaseMixin) Fields() []ent.Field {
  return []ent.Field{
    field.UUID("id", xid.ID{}).Default(xid.New),
    field.Time("created_at").
      Immutable().
      Default(time.Now),
    field.Time("updated_at").
      Default(time.Now).
      UpdateDefault(time.Now),
    field.Time("deleted_at").Optional(),
  }
}

func (BaseMixin) Indexes() []ent.Index {
  return []ent.Index{
    index.Fields("deleted_at"),
  }
}
```

and part of the code main.go

```go

type Comparators struct {
  Comparator string `json:"comparator"`
  Label      string `json:"label"`
  Zone       struct {
    X1 float64 `json:"x1"`
    Y1 float64 `json:"y1"`
    X2 float64 `json:"x2"`
    Y2 float64 `json:"y2"`
  }
  RatioThreshold float64 `json:"ratio_threshold"`
  Times          []struct {
    start string `json:"start"`
    end   string `json:"end"`
  }
}

func (ctrl SceneController) Create(c *gin.Context) {
  resp := ctrl.NewResponse()

  var sceneModel = struct {
    Name             string        `json:"name"`            
    Remark           string        `json:"remark"`          
    ViolationDesc    string        `json:"violation_desc"`    
    ModelID          xid.ID        `json:"model_id"`        
    CamerasID        xid.ID        `json:"cameras_id"`    
    Comparators      []Comparators `json:"comparators"`     
    TriggerThreshold int           `json:"trigger_threshold"` 
    InspectMinuts    int           `json:"inspect_minuts"` 
  }{}

  err = json.NewDecoder(c.Request.Body).Decode(&sceneModel)
  if err != nil {
    resp.ErrorCode = 1
    resp.ErrorMessage = err.Error()
    c.JSON(http.StatusOK, resp)
    return
  }
  ctx := c.Request.Context()

  tx, err := ctrl.DB.Tx(ctx)
  if err != nil {
    resp.ErrorCode = 1
    resp.ErrorMessage = err.Error()
    c.JSON(http.StatusOK, resp)
    return
  }

  for _, item := range sceneModel.Comparators {
    _, err := tx.Scene.Create().
        SetName(sceneModel.Name).
        SetRemark(sceneModel.Remark).
        SetViolationDesc(sceneModel.ViolationDesc).
        SetComparator(item.Comparator).
        SetLabel(item.Label).
        SetTimes(item.Times).
        SetRatioThreshold(item.RatioThreshold).
        SetTriggerThreshold(sceneModel.TriggerThreshold).
        SetInspectMinuts(sceneModel.InspectMinuts).
        Save(ctx)

    if err != nil {
      if rerr := tx.Rollback(); rerr != nil {
        err = fmt.Errorf("%w: %v", err, rerr)
      }
      resp.ErrorCode = 1
      resp.ErrorMessage = err.Error()
      c.JSON(http.StatusOK, resp)
      return
    }

  }

  tx.Commit()

  c.JSON(http.StatusOK, resp)
}
```

**Comment by dybxin** [comment] 2021-04-08 08:47
the version of ent i used is 0.7.0

**Comment by dybxin** [comment] 2021-04-08 09:27
@a8m  i solve this problem use , in the `/ent` same level directory add a `times.go` file.

times.go 

```go
type Time struct { Start, End string }
```

and in schema `scene.go` file 

```go
field.JSON("times", []model.Time{})
```

and in `main.go`

```go
type name struct {
Times          []model.Time `json:"times"`
}
```

In short， anywhere use the declare Time struct.

**Comment by a8m** [comment] 2021-04-08 09:31
Hey @dybxin,
What errors do you get? The only problem I see is that the codegen formats the nested struct-tags incorrectly. For example:
```diff
+[]struct { Start string `json:"start"`}{}`
-[]struct { Start string "json:\"start\""}{}
```

But these anonymous structs are not fully supported and will require you to use named-structs like:

```go
type T { Start string `json:"start,omitempty"` }
[]T{}
```

**Comment by a8m** [comment] 2021-04-08 09:32
> @a8m i solve this problem use , in the `/ent` same level directory add a `times.go` file.
> 
> times.go
> 
> ```go
> type Time struct { Start, End string }
> ```
> 
> and in schema `scene.go` file
> 
> ```go
> field.JSON("times", []model.Time{})
> ```
> 
> and in `main.go`
> 
> ```go
> type name struct {
> Times          []model.Time `json:"times"`
> }
> ```
> 
> In short， anywhere use the declare Time struct.

Great, I missed this comment. 

Let's close this issue then. Thanks 🙏

**Closed** 2021-04-08 09:40 UTC
